### ISSUE TITLE
Design - Hero

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#10]
Chamada principal na home

**Comment by miguelpeixe** [comment]
![home-hero](https://cloud.githubusercontent.com/assets/820752/24506326/7e990020-1533-11e7-81de-623b5b3ec019.jpg)

**Comment by thaisrigolon** [comment]
A gente consegue validar essa proposta de layout no wireframe criado ou só conseguimos validar por essa imagem do layout?

**Comment by miguelpeixe** [comment]
ver #9

**Comment by thaisrigolon** [comment]
Hero aprovado

![hero](https://cloud.githubusercontent.com/assets/18294515/25345047/47d62b6a-28ea-11e7-9812-a0b29ed5166f.png)
