### ISSUE TITLE
Design - Rodapé

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#11]

**Comment by miguelpeixe** [comment]
![footer_01](https://cloud.githubusercontent.com/assets/820752/24616126/9a13992e-1866-11e7-8aa7-950b69820945.png)

**Comment by miguelpeixe** [comment]
O rodapé recebe agora um azul mais claro, que - apesar de não ser o mesmo tom - favorece a relação com o Instituto TIM. Também inclui o formulário de cadastro para a newsletter

http://portal-mapas.conexaobrasil.org/#colophon

![footer](https://cloud.githubusercontent.com/assets/820752/24816552/96b71e9e-1baf-11e7-8ec5-d29dd0ad56eb.png)

**Comment by thaisrigolon** [comment]
Estamos avaliando o rodapé, mas já adiantamos que a proposta está ótima. Uma consideração inicial: inserir a marca do Instituto TIM pequena na frase "Software livre desenvolvido pelo (marca)".

**Comment by miguelpeixe** [comment]
fde7986d8be905131f56ea96209ba29ceeb31613

**Comment by thaisrigolon** [comment]
Rodapé aprovado:

![rodape](https://cloud.githubusercontent.com/assets/18294515/25344990/222185cc-28ea-11e7-9608-d5a8332e1ade.png)
