### ISSUE TITLE
Design - Widget Mapa

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#13]

**Comment by miguelpeixe** [comment]
http://portal-mapas.conexaobrasil.org/rede/

**Comment by thaisrigolon** [comment]
- [x] Seria importante ter alguma ilustração ou elemento que mostrasse ao usuário que ele está nessa página. Como, por exemplo, na página da Comunidade. A variação de cor poderia ajudar. Explorar a paleta de cores.
![1](https://cloud.githubusercontent.com/assets/18294515/25350400/6a9a5bce-28fb-11e7-89b1-3f3c9a1d9aa2.png)

- [x] Alinhar o **blog da rede** com **conheça as iniciativas**
![1](https://cloud.githubusercontent.com/assets/18294515/25350591/086b8350-28fc-11e7-94be-0122f9dba448.png)

- [x] Colocar outra cor na caixa que apresenta os indicadores da instalação
![1](https://cloud.githubusercontent.com/assets/18294515/25351153/20388e90-28fe-11e7-8616-c4b8781b55d2.png)

- [x] Adicionar o indicador de espaços também
![1](https://cloud.githubusercontent.com/assets/18294515/25353599/3ba58b58-2906-11e7-98d1-032a98debac8.png)

- [x] No mapa o pin poderia ser o mesmo do layout
![1](https://cloud.githubusercontent.com/assets/18294515/25350619/1c1d3290-28fc-11e7-932a-2872530820be.png)

- [x] Diminuir os títulos dos posts do blog da rede e das iniciativas
![1](https://cloud.githubusercontent.com/assets/18294515/25350967/4f592c8a-28fd-11e7-8c3c-540696c1425d.png)

**Comment by thaisrigolon** [comment]
Aproximar o box com dados da foto. O box está com distâncias muito próximas das duas infos - cima e baixo. Aproximando fica mais fácil de conectar o quadro com as infos da plataforma certa.

![screen shot 2017-05-08 at 11 00 38 am](https://cloud.githubusercontent.com/assets/18294515/25810309/2062695c-33e6-11e7-8942-26c695cdbb08.png)

**Comment by miguelpeixe** [comment]
Alterações realizadas: http://portal-mapas.conexaobrasil.org/rede/

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
