### ISSUE TITLE
Design - Listas

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#14]

**Comment by miguelpeixe** [comment]
Notícias: http://portal-mapas.conexaobrasil.org/category/uncategorized/
Post único: http://portal-mapas.conexaobrasil.org/2017/03/27/hello-world/
Tutoriais: http://portal-mapas.conexaobrasil.org/tutorials/
Tutorial único: http://portal-mapas.conexaobrasil.org/tutorials/como-fazer-uma-instalacao-local-da-plataforma/

![09-noticias](https://cloud.githubusercontent.com/assets/820752/25183265/7ce160a0-24ed-11e7-8e17-fa72e3d032cd.png)
![10-post](https://cloud.githubusercontent.com/assets/820752/25183328/a29f4e1a-24ed-11e7-8c4b-9b88be8a8890.png)
![04-tutoriais](https://cloud.githubusercontent.com/assets/820752/25183351/b67f4aca-24ed-11e7-816b-e930c336ec30.png)
![05-tutorial](https://cloud.githubusercontent.com/assets/820752/25183354/b88bb84e-24ed-11e7-95fc-aa387bedee6b.png)

**Comment by thaisrigolon** [comment]
- [x] É bem importante também ter uma cor diferente na abertura ou ilustração que identifique que estamos na página específica. 
- [x] Adicionar cores diferentes nos links, como foi feito na página de suporte.
![1](https://cloud.githubusercontent.com/assets/18294515/25354767/acbb00c6-290a-11e7-907a-d58f3916c3a7.png)
- [x] Dar mais destaque no widget de texto
![1](https://cloud.githubusercontent.com/assets/18294515/25358455/dbeb3552-2917-11e7-8e2c-1e44c063c811.png)

**Dúvidas**
- [x] Se não adicionarmos o widget de texto como ficará a página? Ficará com uma coluna vazia? Lembrando que a ideia é ter a newsletter apenas no rodapé.
- [x] Como ficará quando adicionarmos uma foto no post?

**Comment by miguelpeixe** [comment]
Sobre as dúvidas, a página estática terá também a possibilidade template sem barra lateral (widgets). Vou adicionar no design exemplo de foto na página e o modelo de página sem barra lateral.

**Comment by thaisrigolon** [comment]
> Sobre as dúvidas, a página estática terá também a possibilidade template sem barra lateral (widgets). Vou adicionar no design exemplo de foto na página e o modelo de página sem barra lateral.

Ok

**Comment by miguelpeixe** [comment]
Página estática comum: http://portal-mapas.conexaobrasil.org/sample-page/
Página estática "full width": http://portal-mapas.conexaobrasil.org/exemplo-de-pagina-de-full-width/

**Comment by thaisrigolon** [comment]
- [x] Ícone da página de suporte não remete ao tema. Gostaríamos de outra opção.
![1](https://cloud.githubusercontent.com/assets/18294515/25810411/6e7c73f8-33e6-11e7-8d7e-9f4e977a4d94.png)

- [ ] Na página da comunidade mudar as cores de uma das colunas para diferenciar os tipos de pautas. As cores podem estar no título e boxes.
![1](https://cloud.githubusercontent.com/assets/18294515/25810472/945dbb0e-33e6-11e7-85f4-4636d2b452ff.png)

**Página de notícias:** 
- [x] Adicionar ícone, como nas páginas de suporte e tutoriais
- [x] Adicionar cor em textos, como na página de tutoriais. Ainda é a página mais azul.
![1](https://cloud.githubusercontent.com/assets/18294515/25810745/723d879c-33e7-11e7-9954-182d7897a493.png)
- [x] Gostamos da opção do campo rosa, mas pode diminuir um pouco a margem. É importante ter uma opção de página sem o campo rosa. 
![screen shot 2017-05-08 at 11 23 38 am 1](https://cloud.githubusercontent.com/assets/18294515/25810919/f0cb4b08-33e7-11e7-8f2c-4ebc25604278.png)

**Página estática full width (sem widget)**
- [x] Não gostamos muito desse exemplo full width. O texto fica muito longo e cansativo pra ler. Funcionaria se deixasse uma margem maior talvez. Poderia dar outra opção?
http://portal-mapas.conexaobrasil.org/exemplo-de-pagina-de-full-width/

**Dúvidas:**

1) As páginas de notícias devem se assemelhar a esta página: http://portal-mapas.conexaobrasil.org/sample-page/
Para ter uma diferença em relação aos posts dos blogs. É possível?

2) Gostaríamos que tivéssemos a opção de usar a foto ocupando um espaço maior (exemplo da foto 2), além da foto pequena.
![screen shot 2017-05-08 at 11 19 01 am](https://cloud.githubusercontent.com/assets/18294515/25810871/ca2b8116-33e7-11e7-90d3-8f394404b371.png)

![screen shot 2017-05-08 at 11 20 35 am](https://cloud.githubusercontent.com/assets/18294515/25810885/d352abd4-33e7-11e7-941e-fc887ee9b3d2.png)

**Comment by miguelpeixe** [comment]
Os ícones ganharam um novo estilo de exibição, todos ícones de cabeçalho de página possuem estão em um círculo conectado à linha de cabeçalho do site.

 - Novo ícone de suporte: http://portal-mapas.conexaobrasil.org/suporte/
 - Página *full* com menor grid, menor margem de excerto rosa e exemplos de uso de imagem full: http://portal-mapas.conexaobrasil.org/exemplo-de-pagina-de-full-width/ http://portal-mapas.conexaobrasil.org/sample-page/
 - Os excertos em rosa das páginas são sempre opcionais, dependem do preenchimento do campo extra na edição da página
 - Página notícias (e post da notícia) com ícones e também optei por inserir as subcategorias de notícias no cabeçalho, para melhor preencher e facilitar acesso à temas específicos: http://portal-mapas.conexaobrasil.org/noticias/ http://portal-mapas.conexaobrasil.org/2017/05/09/class-aptent-taciti-sociosqu-ad-litora-torquent-per-conubia-nostra-per-inceptos-himenaeos/

**Comment by thaisrigolon** [comment]
Diminuir a largura do widget de texto e da categoria. Diminuir um pouco a fonte também. 

Em computadores com resolução de tela menor os textos ficam enormes, cobrem um terço da página. Chama muita atenção e deixa o texto da matéria em segundo plano.
![image010](https://cloud.githubusercontent.com/assets/18294515/25959599/80e932ea-364a-11e7-9d82-cceb068a6e94.jpg)

**Comment by miguelpeixe** [comment]
Estilo e margem das barras laterais ajustados. Largura das margens na página do membro da rede se manteve igual pela relevância das informações alí contidas, aguardo aprovação dessa decisão.

**Comment by thaisrigolon** [comment]
> Estilo e margem das barras laterais ajustados. Largura das margens na página do membro da rede se manteve igual pela relevância das informações alí contidas, aguardo aprovação dessa decisão.

Ótimo, podemos manter assim.

**Comment by thaisrigolon** [comment]
Issue homologada. 

Sobre o pedido da página de comunidade, o layout já está sendo homologado na issue #17
