### ISSUE TITLE
Design - Página Linha do Tempo

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#15]

**Comment by miguelpeixe** [comment]
![timeline](https://cloud.githubusercontent.com/assets/820752/25004690/f3ad386a-202b-11e7-924a-de3f02280991.png)

**Comment by miguelpeixe** [comment]
http://portal-mapas.conexaobrasil.org/linha-do-tempo/

**Comment by miguelpeixe** [comment]
![02-timeline](https://cloud.githubusercontent.com/assets/820752/25184673/789147a0-24f1-11e7-976f-a3dcdeefdcc1.png)

**Comment by thaisrigolon** [comment]
- [x] Seria importante ter alguma ilustração ou elemento que mostrasse ao usuário que eles está nessa página. Como, por exemplo, na página da Comunidade.
![1](https://cloud.githubusercontent.com/assets/18294515/25347444/586d9196-28f1-11e7-8f97-e5cce42b6423.png)


- [x] Também seria interessante se, ao rolar a página, os blocos da linha do tempo fossem aparecendo. É possível?

**Comment by miguelpeixe** [comment]
Qual ilustração da Comunidade você faz referência para a linha do tempo?

Sobre o segundo item, excelente ideia, vou trabalhar nisso.

**Comment by thaisrigolon** [comment]
![1](https://cloud.githubusercontent.com/assets/18294515/25357939/182627c2-2916-11e7-8abe-9218765d5a98.png)

**Comment by miguelpeixe** [comment]
A região destacada é um gráfico de contribuições no repositório do mapasculturais. Ainda sim, acha uma boa ideia ilustrar as páginas de linha do tempo e página das instâncias?

**Comment by thaisrigolon** [comment]
> A região destacada é um gráfico de contribuições no repositório do mapasculturais. Ainda sim, acha uma boa ideia ilustrar as páginas de linha do tempo e página das instâncias?

Sim, gostaríamos que essas páginas tivessem ilustrações ou algumas cores diferentes na abertura como foi feito na página de suporte, por exemplo:

![1](https://cloud.githubusercontent.com/assets/18294515/25406491/35365d10-29dd-11e7-9a74-745f57322762.png)

**Comment by miguelpeixe** [comment]
Ok

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
