### ISSUE TITLE
Design - Página Inicial do Suporte

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#16]

**Comment by miguelpeixe** [comment]
http://portal-mapas.conexaobrasil.org/suporte/

![03-suporte](https://cloud.githubusercontent.com/assets/820752/25183412/e9ee807e-24ed-11e7-952c-dbb687b8a650.png)

**Comment by thaisrigolon** [comment]
- [ ] Manter um padrão: 
![1](https://cloud.githubusercontent.com/assets/18294515/25348032/4330456a-28f3-11e7-9a45-2f0890d9f84c.png)

**Comment by miguelpeixe** [comment]
Qual padrão você se refere? O botão de tutoriais do cabeçalho (não o campo de busca) é um link para acesso direto à página de tutoriais (http://portal-mapas.conexaobrasil.org/tutorials/)

**Comment by thaisrigolon** [comment]
Certo. Então vamos manter da forma que está.
