### ISSUE TITLE
Design - Página Inicial da Comunidade

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#17]

**Comment by miguelpeixe** [comment]
http://portal-mapas.conexaobrasil.org/comunidade/

**Comment by miguelpeixe** [comment]
Em progresso:

![08-comunidade](https://cloud.githubusercontent.com/assets/820752/25183090/f3da9060-24ec-11e7-88c3-52cf0f5902f8.png)

Estamos estudando o comportamento do plugin Delibera para poder ter um design fiel ao fluxo da ferramenta.

**Comment by thaisrigolon** [comment]
Seria importante ter uma diferenciação de cor entre as partes **pautas em discussão** e **propostas de pauta**

![1](https://cloud.githubusercontent.com/assets/18294515/25355291/7dff7788-290c-11e7-94ae-091551770ee5.png)

**Comment by miguelpeixe** [comment]
Página da comunidade redesenhada para se adequar às últimas definições de design do site e também de acordo com o fluxo de funcionamento do plugin Delibera

![08-comunidade_02](https://cloud.githubusercontent.com/assets/820752/26126837/7b370be4-3a5d-11e7-8ccc-d8fc9b0d8925.png)

**Comment by thaisrigolon** [comment]
Ficou bem legal! Apenas algumas observações (veja se é possível realizar):

- [x] Os botões estão em tamanhos diferentes, precisa ficar no mesmo padrão:
![1](https://cloud.githubusercontent.com/assets/18294515/26212233/45f258d4-3bcb-11e7-9907-726f8c89bf05.png)

- [x] Daria pro número ficar mais próximo do botão? No momento está confuso porque parece que o número 1 está entre as duas imagens.
![1](https://cloud.githubusercontent.com/assets/18294515/26212251/5551de76-3bcb-11e7-9355-82e2b58ad393.png)

- [x] Separar os blocos de propostas de pauta e pautas com resolução:
![1](https://cloud.githubusercontent.com/assets/18294515/26212183/25213eae-3bcb-11e7-9ae7-8dcc68823dd1.png)

**Comment by miguelpeixe** [comment]
Sobre o tamanho do botão, o erro foi identificado assim que publiquei o printscreen e já corrigido. O restante estou trabalhando agora.

**Comment by miguelpeixe** [comment]
![08-comunidade_03](https://cloud.githubusercontent.com/assets/820752/26220320/919b77a8-3be8-11e7-9c5f-bb8289cebcde.png)

**Comment by thaisrigolon** [comment]
É possível alterar a distância do número na outra coluna também?

![1](https://cloud.githubusercontent.com/assets/18294515/26220518/52d97d34-3be9-11e7-8336-69901828c963.png)

**Comment by miguelpeixe** [comment]
![captura de tela de 2017-05-24 16-38-01](https://cloud.githubusercontent.com/assets/820752/26422247/743c9e38-409f-11e7-8eec-1c2b4972d688.png)

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
