### ISSUE TITLE
Wireframe - Comunidade/delibera

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#18]

**Comment by miguelpeixe** [comment]
http://dev.aparabolica.com.br/mapasculturais/wireframe/html/community.html

**Cabeçalho da página** - Apresentação da comunidade, alguns indicadores técnicos e link para acesso do GitHub e documentação técnica

**Seção delibera** - Apresentação, listagem de categorias e listagem de pautas ativas e pendentes

**Comment by thaisrigolon** [comment]
Esse wireframe está ok, lembrando que vamos passar os textos para a página até o dia **05/04**.
