### ISSUE TITLE
Definir licença de código

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#19]
Nós usamos MIT para a maioria dos projetos. A melhor referência que conheço para saber as diferenças entre as licenças este site, feito pelo Github:

https://choosealicense.com

**Comment by thaisrigolon** [comment]
Gostaríamos que a licença fosse GPL (“General Public License”). Mas, vocês podem seguir a referência de um outro projeto nosso, em que o fornecedor listou as licenças para os componentes e bibliotecas utilizadas:

![credits](https://cloud.githubusercontent.com/assets/18294515/24260873/f293a7ce-0fd3-11e7-81b5-88de7817d810.png)

**Comment by vgeorge** [comment]
Podemos usar a GPL, só precisamos confirmar se os códigos de terceiros são compatíveis. O Delibera parece que usa GPL 3.0, mas [pedi confirmação](https://github.com/redelivre/delibera/issues/150).

**Comment by vgeorge** [comment]
O Delibera é GPL: https://github.com/redelivre/delibera#licen%C3%A7a

Agora basta adicionar a declaração de licença no README e o LICENSE.txt.

**Comment by thaisrigolon** [comment]
Beleza!

**Comment by vgeorge** [comment]
Movi os termos da licença para o final do README. Pelo que entendi a recomendação da FSF é de colocar o disclaimer no topo dos arquivos de código-fonte, mas não no readme. De qualquer jeito me parece cauteloso demais e difícil de manter a colocação de termos da licença em todos os arquivos, no readme me parece suficiente.

**Comment by thaisrigolon** [comment]
Ok
