### ISSUE TITLE
Wireframe - Tela Inicial

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#2]

**Comment by miguelpeixe** [comment]
http://dev.aparabolica.com.br/mapasculturais/wireframe/html/

**Cabeçalho** - Logo, menu e busca

**Hero (eyecandy)** - Slogan/descrição curta, convite ao acesso às principais áreas, resumo dos dados das instalações (destacando impacto/alcance do software)

**Seção conteúdo dinâmico** - Mais informações sobre o MC, últimos posts e formulário para newsletter

**Convite à comunidade** - Seção constante em todas as páginas, convida usuário à participar da comunidade, apresenta critérios/métodos de participação e importância do debate democrático na contribuição do software

**Rodapé** - Links institucionais (eventual licença de uso, acesso à termos de uso, etc)

**Comment by thaisrigolon** [comment]
- [x] **Alterar Hero (eyecandy) para:** Software livre para gestão cultural e mapeamento colaborativo. _(essa frase será editável, certo?)_


- [x] Alterar os dois indicadores atuais para: **X** plataformas 
![1](https://cloud.githubusercontent.com/assets/18294515/24198254/e47f9472-0ee3-11e7-8549-4c2d1b4a5e49.png)


- [x] Últimas novidades trocar por **Notícias** e referenciar à página  estática simples para as notícias institucionais (blog institucional)
![1](https://cloud.githubusercontent.com/assets/18294515/24198557/24da0402-0ee5-11e7-9a34-aae64b55d022.png)


- [x] Blog dos gestores alterar para **Blog da rede**.
![1](https://cloud.githubusercontent.com/assets/18294515/24198608/4b446484-0ee5-11e7-83e3-8b903af8c538.png)


- [x] Vamos ter apenas 1 tipo de newsletter. Entendemos que será importante os gestores terem conhecimento de alguns temas mais técnicos e vice-e-versa. Deixar apenas o campo para assinar a newsletter que será utilizada com o serviço do mailchimp.
![1](https://cloud.githubusercontent.com/assets/18294515/24198691/a33dd7a6-0ee5-11e7-9b62-04ec670a035c.png)


- [x] Tirar os botões de redes sociais.
![1](https://cloud.githubusercontent.com/assets/18294515/24198312/248bc6b2-0ee4-11e7-8e77-442da489941b.png)


- [x] O menu deve ser configurado da seguinte forma como menu único:
**Sobre a iniciativa**
Sub-páginas deste item: O que é > Histórico > Parceiros
**Sobre o sistema**
Sub-páginas deste item: Mapas como serviço > Suporte ao usuário
**Notícias**
**Contato**


Referência para este menu:
![1](https://cloud.githubusercontent.com/assets/18294515/24198447/ba570076-0ee4-11e7-8fc1-7725da32e2e7.png)


- No rodapé ter um mapa do site. Referência:
![1](https://cloud.githubusercontent.com/assets/18294515/24198505/edbfd492-0ee4-11e7-8b76-69b3d96a51d4.png)

**Comment by miguelpeixe** [comment]
As alterações de texto foram realizadas no wireframe: http://dev.aparabolica.com.br/mapasculturais/wireframe/html/index.html

A frase do *hero* será editável sim, assim como menus e submenus do cabeçalho e rodapé. Também ok em relação à estrutura da navegação de rodapé, o design contemplará essa diagramação

Também incluí uma referência à widgets abaixo do formulário de newsletter (ele será um widget também, portanto toda a coluna será dinâmica para organizar widgets)

O formulário de newsletter também foi alterado na página de suporte

510ee2242679e894639ba3112eda6b537d93b698

**Comment by thaisrigolon** [comment]
Ok, obrigada.
