### ISSUE TITLE
Wireframe - Login

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#20]
Criar área para login dos usuários cadastrados na plataforma para publicarem posts.

**Comment by miguelpeixe** [comment]
Recomendo o uso da área de login do próprio WordPress, que já contempla o processo para recuperação de senha. O logo da área de login pode ser customizado.

![WordPress Login](https://codex.wordpress.org/images/6/60/login_form.png)

**Comment by thaisrigolon** [comment]
Ok! Podemos seguir assim.
