### ISSUE TITLE
Tutoriais (Custom Post Type)

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#21]
Criar definição de Custom Post Type de Tutoriais com as propriedades: Versão do Tema, Tags e Complexidade. 

@thaisrigolon, qual o perfil na plataforma de quem vai produzir este conteúdo? Pensamos em apenas Administradores e Editores. Os mantenedores poderiam editar apenas o perfil e o blog de uma instalação.

**Comment by thaisrigolon** [comment]
@vgeorge, podemos manter a permissão para Administradores, Editores e Mantenedores? Seria bem importante que as secretarias também tivessem a permissão para publicar tutoriais específicos.

**Comment by vgeorge** [comment]
Sim, podemos deixar Administradores, Editores e Mantenedores. Sugerimos que o Mantenedor não tenha permissão para publicar, assim um Editor ou Administrador obrigatoriamente deverá revisar a publicação.

Como os tutoriais são conteúdos que terão destaque no site, seria interessante pensar um guia de estilo para que as publicações tenham boa qualidade.

**Comment by thaisrigolon** [comment]
Ok.

**Comment by vgeorge** [comment]
- [x] Alterar "More info's" para "Additional info"
- [x] Usar somente "agents" and "maintainers" ao invés de "for agents.."
- [x] Localização e tradução ao pt de todos os widgets
- [x] Complexidade deve ser um dropdown com as opções "easy", "medium", "advanced"

**Comment by vgeorge** [comment]
Widgets ainda aparecem em inglês:

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/post.php?post=44&action=edit

**Comment by cabelotaina** [comment]
Nao entendi essa pode colocar um print...

seria isso

![image](https://user-images.githubusercontent.com/1827173/36803045-48fd4f24-1c95-11e8-967e-34c60552024f.png)

**Comment by vgeorge** [comment]
O related versions ainda está em inglês. Para traduzir coloque a função __('string', 'pmc'), gere o novo .pot com `grunt pot` e traduza com o Poedit.

**Comment by vgeorge** [comment]
@miguelpeixe, o "Related Versions" foi traduzido, mas continua aparecendo em inglês, sabe o porquê?

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/post.php?post=44&action=edit

**Comment by cabelotaina** [comment]
Feito, estava __("Relate Versions") e deveria ser __("Related Versions", "pmc").

**Comment by Nathlis** [comment]
- [ ] Está ocorrendo um erro quando você cria um Tutorial para GESTORES.

![1](https://user-images.githubusercontent.com/18741130/39593366-e79ccb4c-4edf-11e8-9059-4c85030658ed.png)

Se você atualizar para agentes dá certo:
![2](https://user-images.githubusercontent.com/18741130/39593398-02531b58-4ee0-11e8-8fb5-96f4e2dc5526.png)

E depois mudar de novo para Gestores dá certo:

![3](https://user-images.githubusercontent.com/18741130/39593420-0ef859fe-4ee0-11e8-89e9-fe08703671ab.png)

**Comment by Nathlis** [comment]
Aprovado.
