### ISSUE TITLE
Metadados da Instalação

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#22]
As informações sobre uma instalação serão armazenadas como metadados do usuário mantenedor, que poderá editá-las em seu painel de controle. As seguintes propriedades estão previstas:

- URL da página inicial;
- E-mail de contato;
- Link para código-fonte;
- Coordenadas geográficas;
- Estatísticas da Instalação.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
