### ISSUE TITLE
Edição de Linha do Tempo

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#24]
Habilitar edição de linha do tempo no painel de controle

**Comment by vgeorge** [comment]
Está implementado o formulário de edição, onde o usuário pode definir título, texto e data para itens da linha do tempo. As datas podem ser descritas no formato YYYY, YYYY-MM e YYYY-MM-DD e será gerado o texto localizado para o idioma habilitado no WP:   ![captura de tela 2017-05-30 as 15 33 26](https://cloud.githubusercontent.com/assets/329694/26598996/6a4c46a0-454d-11e7-8d30-a51ab0a1dcf3.png)

**Comment by vgeorge** [comment]
A edição de eventos da timeline agora está disponível no ambiente de validação. Aqui está o link para a página da timeline: http://portal-mapas.conexaobrasil.org/timeline/

**Comment by vgeorge** [comment]
@thaisrigolon Eu adicionei alguns eventos, é possível alterá-los na área administrativa.

**Comment by thaisrigolon** [comment]
O teste de vocês foi feito no ambiente local, certo?
No link http://portal-mapas.conexaobrasil.org/linha-do-tempo/ ainda não conseguimos testar?

**Comment by vgeorge** [comment]
O link correto é: http://portal-mapas.conexaobrasil.org/timeline/

Este último que você colocou fazia parte da validação de layout e será removido.

**Comment by thaisrigolon** [comment]
Ok, consegui adicionar um evento. Mas em qual local eu faço o gerenciamento dos eventos anteriores?
Tem algum local no WP que centraliza todos os eventos criados da linha do tempo?

**Comment by vgeorge** [comment]
Na seção "Timeline" do menu administrativo existe a opção "All items", que lista as entradas já cadastradas.

**Comment by thaisrigolon** [comment]
- [ ] Não é possível colocar um período de ocorrência como, por exemplo: 2003-2008
- [ ] Só está aparecendo 10 eventos na linha do tempo. Adicionei mais de 10 e os outros não aparecem...

**Comment by thaisrigolon** [comment]
A linha do tempo está desconfigurada... só aparecem os textos:

![1](https://user-images.githubusercontent.com/18294515/28136210-3dc67846-671f-11e7-82ba-05f826c41e5e.png)

**Comment by vgeorge** [comment]
http://portal-mapas.conexaobrasil.org/timeline/

Esse é o meu screenshot, você vê diferente?

<img width="512" alt="image" src="https://user-images.githubusercontent.com/329694/28653001-875efb34-7261-11e7-8abf-b7704280b62c.png">

**Comment by thaisrigolon** [comment]
Agora voltou a funcionar, mas continua não aparecendo mais de 10 eventos na linha do tempo e não é possível colocar um período de ocorrência como, por exemplo: 2003-2008

![1](https://user-images.githubusercontent.com/18294515/28671023-9645ce3e-72b1-11e7-94d5-38bdbca3a779.png)

**Comment by vgeorge** [comment]
Resolvi a limitação de itens, adicionei períodos e melhorei a tradução. Miguel vai revisar a exibição das datas por extenso que estão quebrando a visualização:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/329694/29041715-579a8800-7b8a-11e7-8868-ff47653b978e.png">

**Comment by miguelpeixe** [comment]
O estilo das datas foi atualizado para ser mais flexível com tamanhos. Diminuí um pouco o tamanho do texto (para evitar quebras de linhas desnecessárias) e forcei quebra de linha (com estilo resolvido) para casos de início e fim determinados.

**Comment by thaisrigolon** [comment]
É possível deixar as datas de início/fim na mesma linha?
![1](https://user-images.githubusercontent.com/18294515/29334855-30588d7c-81df-11e7-9a94-35b9d46d76b4.png)

**Comment by miguelpeixe** [comment]
Feito

**Comment by thaisrigolon** [comment]
Ótimo! Homologado.
