### ISSUE TITLE
Página estática: Parceiros

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#26]
Adicionar as marcas de todos os parceiros na página estática **Parceiros**:

--- 
O projeto Mapas Culturais conta com uma rede formada por organizações, estados, municípios, gestores e desenvolvedores que trabalham de forma colaborativa para o aprimoramento e escalabilidade da plataforma.

[marcas.docx](https://github.com/institutotim/wp-theme-mapasculturais/files/930952/marcas.docx)

---
(observação: o arquivo de marcas será atualizado, com link clicável para cada site. No entanto, seria importante termos essa visão inicial no wireframe)

**Comment by miguelpeixe** [comment]
http://portal-mapas.conexaobrasil.org/parceiros/

![11-parceiros](https://cloud.githubusercontent.com/assets/820752/25192482/bc4224de-2509-11e7-8cea-8d7a2f20a58d.png)

**Comment by thaisrigolon** [comment]
- [x] Seria importante ter alguma ilustração ou elemento que mostrasse ao usuário que ele está nessa página. Como, por exemplo, na página da Comunidade. A variação de cor poderia ajudar. Explorar a paleta de cores.
![1](https://cloud.githubusercontent.com/assets/18294515/25357651/fc852a5a-2914-11e7-8465-756d18e6920f.png)

- [x] As marcas do Instituto TIM e do MinC precisam estar maiores do que as outras, mas não tão grandes também. Para todas as marcas (além do Instituto TIM e MinC) utilizar o seguinte padrão de dimensão:
![1](https://cloud.githubusercontent.com/assets/18294515/25357700/2b71120c-2915-11e7-93de-d2964de0e40e.png)

- [x] Diminuir os espaço entre as marcas e as linhas

- [x] Separar as marcas da seguinte forma (estamos separando por instituições, prefeituras e governos): 
[marcas.docx](https://github.com/institutotim/wp-theme-mapasculturais/files/953098/marcas.docx)

**Comment by thaisrigolon** [comment]
Aproximar título do box, aumentar a letra pode ser uma opção:
![screen shot 2017-05-08 at 11 06 37 am](https://cloud.githubusercontent.com/assets/18294515/25810502/af2003d4-33e6-11e7-89ea-21f9289dcc64.png)

**Comment by miguelpeixe** [comment]
alterações realizadas: http://portal-mapas.conexaobrasil.org/parceiros/

**Comment by thaisrigolon** [comment]
Por favor, alterar o texto do box rosa para:

> Mapas Culturais foi criado pelo Instituto TIM em parceria com a Secretaria de Cultura do Município de São Paulo, a primeira a adotar a plataforma, em 2014. Atualmente, a solução está em operação no Ministério da Cultura, em estados e municípios de todas as regiões do Brasil e até no exterior.

Também inserir a marca da prefeitura de São Paulo na primeira linha, depois da marca do MinC e diminuir os logos da segunda e terceira linha de forma que formem uma linha só:
![1](https://cloud.githubusercontent.com/assets/18294515/25964787/6b0aaeec-365c-11e7-8da6-fc4b18d6824e.png)

**Comment by miguelpeixe** [comment]
Página atualizada: http://portal-mapas.conexaobrasil.org/parceiros/

Optei por inserir o logo da prefeitura antes do MinC, por protocolo do manual de identidade do governo federal. Não é permitido que nenhuma marca esteja à direita da marca do governo.

**Comment by miguelpeixe** [comment]
O texto da página Rede também foi atualizado com o mesmo texto da página parceiros: http://portal-mapas.conexaobrasil.org/rede

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
