### ISSUE TITLE
Design - Mapa da rede / página da instância

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#27]

**Comment by miguelpeixe** [comment]
http://portal-mapas.conexaobrasil.org/rede/
http://portal-mapas.conexaobrasil.org/author/vgeorge/

![06-rede](https://cloud.githubusercontent.com/assets/820752/25183523/3303893a-24ee-11e7-80db-d8536ca12521.png)
![07-instancia](https://cloud.githubusercontent.com/assets/820752/25183522/32fd2cac-24ee-11e7-992b-a8300bf54788.png)

**Comment by thaisrigolon** [comment]
As alterações da página do mapa da rede foram mencionadas na issue #13 

---

### Página da instância
- [x] A cor do nome da secretaria precisa ser outra para diferenciar do nome da instalação
![4](https://cloud.githubusercontent.com/assets/18294515/25351194/4e7abf26-28fe-11e7-8569-1417ae336c3d.png)

- [x] Diminuir os título dos posts
![1](https://cloud.githubusercontent.com/assets/18294515/25351223/616fc810-28fe-11e7-8d6d-e19768c1637c.png)

- [x] Quando o indicador da estatística for alterado é possível mudar a cor do gráfico?
![5](https://cloud.githubusercontent.com/assets/18294515/25351242/754a4e64-28fe-11e7-8adf-964c7588b69c.png)

- [x] Adicionar ícones de contato (email, facebook, twitter, instagram, github, etc..) É possível?
![6](https://cloud.githubusercontent.com/assets/18294515/25351274/97ea21f6-28fe-11e7-8dcb-5f5f15b63e0b.png)

- [x] Adicionar cores diferentes nos links, como foi feito na página de suporte.
![1](https://cloud.githubusercontent.com/assets/18294515/25354767/acbb00c6-290a-11e7-907a-d58f3916c3a7.png)

**Comment by thaisrigolon** [comment]
Aproximar o box com dados da foto. O box está com distâncias muito próximas das duas infos - cima e baixo. Aproximando fica mais fácil de conectar o quadro com as infos da plataforma certa.

![screen shot 2017-05-08 at 11 00 38 am](https://cloud.githubusercontent.com/assets/18294515/25810309/2062695c-33e6-11e7-8942-26c695cdbb08.png)

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
