### ISSUE TITLE
Design - Página inicial

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#28]
http://portal-mapas.conexaobrasil.org

![01-home](https://cloud.githubusercontent.com/assets/820752/25184628/5f1c6570-24f1-11e7-959c-72bc21cbb996.png)

**Comment by thaisrigolon** [comment]
É possível deixar o botão para rolar a página até o final? No momento ele só está na primeira sessão...

![1](https://cloud.githubusercontent.com/assets/18294515/25184778/c99af2ea-24f1-11e7-8008-88ca3fb77dd0.png)

**Comment by miguelpeixe** [comment]
A intenção do botão é indicar o usuário para passar para a próxima sessão, não descer até o rodapé. Ele existe porque o cabeçalho+hero tem sempre exatamente a altura do navegador, por isso o usuário nunca terá uma indicação (além dessa) de que existe mais conteúdo para baixo.

Não recomendo fazer esse botão rolar até o final, o usuário pode ficar confuso porque mutias vezes esse botão é sua primeira interação e com a rolagem até o final perderá referência de como seguir adiante em sua navegação.

**Comment by thaisrigolon** [comment]
A ideia seria ter o botão para ir para as próximas sessões na verdade, acho que não expliquei bem.
Nas instalações de mapas temos a seta que fica no menu lateral e facilita a navegação:
Exemplo: http://mapaculturalbh.pbh.gov.br/

**Comment by miguelpeixe** [comment]
Entendi, ainda sim, a única sessão que tem o comportamento de tela cheia estabelecido é o cabeçalho+hero. As áreas seguintes tem altura fluida, que o usuário naturalmente terá que rolar para continuar visualizando a área (principalmente quando se chega na área de notícias/blog da rede). Se o usuário rolar através de uma navegação de botão poderá perder conteúdo no caminho.

**Comment by thaisrigolon** [comment]
- [x] Manter separação da barra de notícias com o blog da rede mantendo a cor rosa até o final da parte:
![1](https://cloud.githubusercontent.com/assets/18294515/25345926/9a36d4fc-28ec-11e7-808c-aa988635f708.png)

- [x] Alterar a cor do botão "veja mais notícias"
![1](https://cloud.githubusercontent.com/assets/18294515/25345957/af2af960-28ec-11e7-8182-2e0aeff05bca.png)

- [x] Diminuir um pouco os títulos dos posts/matérias
![1](https://cloud.githubusercontent.com/assets/18294515/25346009/d151cb36-28ec-11e7-9166-70f8e56b0fd2.png)

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
