### ISSUE TITLE
Metadados da Instância

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#29]
- [x] Equipe
   - Email
   - Nome
   - Posição
 - [x] Contato
- [x] Coordenadas

**Comment by vgeorge** [comment]
Adicionei os campos de contato e de equipe e renomeei o role para "instância".

**Comment by vgeorge** [comment]
@thaisrigolon É possível editar os metadados no perfil do usuário com role "instância":

![Captura de Tela 2017-06-14 às 18.04.25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58c6e9d95ee3431a0002647c/125516c66e82c728ace21e0d46cb958a379791a8cfedba039058fc95691477227e49f37d3dd4b768beee9b124f5e46b2415c4146f9eb9539e6f4632adf0f4fffdb7f5a7c953412fdbb854bbd01b226884f85b5b4834f93ed3b22f5979d0d6f405147d4a61760e28b41da5af041e0495ca3173167ee76347e4e900c38.png)

**Comment by vgeorge** [comment]
Dei-me conta agora que falta o campo de coordenadas, a issue volta para "in progress".

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
