### ISSUE TITLE
Wireframe - Linha do Tempo

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#3]

**Comment by thaisrigolon** [comment]
Algumas dúvidas:

- O conteúdo dessa página poderá ser atualizado sempre, né? A ideia é ter sempre conteúdo novo para esse linha do tempo e também precisamos ter a possibilidade de alterar textos dos itens antigos.

- Podemos incluir pequenas fotos nos itens?
![1](https://cloud.githubusercontent.com/assets/18294515/24170986/7a0a936c-0e61-11e7-8a48-434acfea1502.png)

**Comment by miguelpeixe** [comment]
Sim, o conteúdo será dinâmico e poderá ser adicionado/editado.

Alterei o wireframe para exemplificar o uso de imagens (também poderão ser submetidos vídeos do YouTube/Vimeo e tweets)

http://dev.aparabolica.com.br/mapasculturais/wireframe/html/timeline.html

e1cdf316aba2c901cd3844954e249012b0cb4684

**Comment by thaisrigolon** [comment]
Ótimo, é isso mesmo. Obrigada.
