### ISSUE TITLE
Páginas de erro

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#30]
Quando o servidor retorna status 4xx ou 5xx deve ser exibida página de erro.

**Comment by vgeorge** [comment]
- [x] Remover campo de buscar de busca por tutoriais nesta página
- [x] Remover caixa de texto branca
- [x] Substituir "404 Error" por "Página não encontradar" 
- [x] Substituir "This is somewhat embarrassing, isn’t it?" por "Volte à página inicial (com link) ou faça uma busca."

**Comment by vgeorge** [comment]
Exemplo de link inválido para teste:

http://hmg.mapasculturais.medialab.ufg.br/aosidpoasidpoaisdpo

**Comment by thaisrigolon** [comment]
- [ ] Alterar texto para:

_Página não encontrada
Volte à página inicial ou faça uma _nova_ busca._

![1](https://user-images.githubusercontent.com/18294515/37346497-38b64bf2-26ae-11e8-824e-4e08a1eca109.png)

- [ ] Quando clicamos no link "página inicial" não funciona, ou seja, o usuário não é direcionado para a home.

**Comment by vgeorge** [comment]
Feito.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
