### ISSUE TITLE
Thumbnail na Timeline

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#31]
Os thumbnails estão habilitados, mas não aparecem corretamente.

**Comment by miguelpeixe** [comment]
fixed with aba25dc4fd59c4a9baee95389f91e6fb57040c61

**Comment by miguelpeixe** [comment]
Por conta da implementação de um novo `image_size`, é necessário fazer upload de nova imagem para testar a thumbnail, ou instalar o plugin [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) para gerar as thumbnails novamente.

**Comment by vgeorge** [comment]
@thaisrigolon Thumbnails parecem estar funcionando corretamente, sugiro encerramento.
