### ISSUE TITLE
Scroll na Timeline

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#32]
Animação na rolagem não está funcionando

**Comment by miguelpeixe** [comment]
fixed with f402b9cd291c60420c91b74d9264bb129264e786

**Comment by vgeorge** [comment]
@thaisrigolon Havia um problema na rolagem que foi corrigido. A menos que você identifique alguma alteração necessária para o scroll da página de timeline, sugiro o encerramento do issue.

Link para verificação: http://portal-mapas.conexaobrasil.org/timeline/

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
