### ISSUE TITLE
Layout - Home

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#33]
- [x] Clarear um pouco o azul escuro do fundo. Em alguns computadores está parecendo preto:
![1](https://user-images.githubusercontent.com/18294515/28834750-9235dd28-76b9-11e7-9c21-0a2ac619741f.png)

- [x] O título Mapas Culturais não está aparecendo acima do texto. Por favor, adicionar novamente e colocar em amarelo para dar destaque (utilizar o mesmo amarelo do logo acima):
![1](https://user-images.githubusercontent.com/18294515/28834524-dccf3682-76b8-11e7-953b-744250a07918.png)

- [x] Diminuir um pouco o seguinte texto:
![1](https://user-images.githubusercontent.com/18294515/28834555-ef3fe29e-76b8-11e7-92c4-dea54a9c1230.png)

- [x] Alterar o texto "busque qualquer coisa" para "Busca":
![1](https://user-images.githubusercontent.com/18294515/28834632-2d91585c-76b9-11e7-8ba1-a3821ca2dd41.png)

- [x] Tirar o pontilhado do lado rosa:
![1](https://user-images.githubusercontent.com/18294515/28834673-4f31d8f6-76b9-11e7-8a53-00485306456f.png)

- [x] Suavizar o pontilhado do lado branco, puxando a cor para o cinza:
![1](https://user-images.githubusercontent.com/18294515/28834706-6b59c548-76b9-11e7-841b-9f7bb7e6583e.png)

- [x] Tem uma linha branca aparecendo quase no final da página:
![1](https://user-images.githubusercontent.com/18294515/28834790-b526c126-76b9-11e7-9fde-22183caa9a1f.png)

- [x] Aumentar a marca do Instituto TIM:
![1](https://user-images.githubusercontent.com/18294515/28834725-7a0429f8-76b9-11e7-8b8e-ed3196a0287c.png)

**Comment by thaisrigolon** [comment]
- [x] Clarear um pouco mais o azul... em algumas telas ainda está bem escuro:
![auzl](https://user-images.githubusercontent.com/18294515/28984094-a9ba5098-7932-11e7-871b-5e192ad1f5f8.png)

- [x] Como as letras foram diminuídas ficou muito espaço após o texto em resolução no MAC:
![1](https://user-images.githubusercontent.com/18294515/28984218-466629bc-7933-11e7-8766-f635b39fbbf0.png)



Diminuir um pouco, como está na resolução do windows:
![1](https://user-images.githubusercontent.com/18294515/28984141-e29dac20-7932-11e7-9634-66534cbf534c.png)

- [x] Como a letra foi diminuída, perdeu a centralização:
![1](https://user-images.githubusercontent.com/18294515/28984173-000d0d78-7933-11e7-9d20-b72ea259ceb7.png)

- [x] Aproximar mais o nome do autor e data do título:
![1](https://user-images.githubusercontent.com/18294515/28984192-1ad75f50-7933-11e7-8545-a0a9485ef389.png)

**Comment by miguelpeixe** [comment]
Ajustes realizados

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
