### ISSUE TITLE
Layout - Mapa da Rede

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#34]
Na caixa em amarelo, alterar para o seguinte texto deixando o Instituto TIM em negrito e com link para o site:

> Mapas Culturais foi criado pelo **[Instituto TIM](http://institutotim.org.br/)** em parceria com a Secretaria de Cultura do Município de São Paulo, a primeira a adotar a plataforma, em 2014. Atualmente, a solução está em operação no Ministério da Cultura, em estados e municípios de todas as regiões do Brasil e até no exterior. Em 2015, Mapas Culturais passou a ser a plataforma oficial do Sistema Nacional de Informações e Indicadores Culturais (SNIIC), sendo o sistema oficial para mapeamento colaborativo e gestão da cultura do Ministério da Cultura.

![1](https://user-images.githubusercontent.com/18294515/28835462-c3b0ca28-76bb-11e7-9d8f-35da91fe86fb.png)

**Comment by thaisrigolon** [comment]
- [x] A parte azul inteira deve aparecer no primeiro plano para o usuário. Como aumentamos o texto, agora a parte de indicadores das entidades não aparece, só quando o usuário rola a página.
Sugerimos aumentar a largura do quadro amarelo e diminuir um pouco a letra.

![1](https://user-images.githubusercontent.com/18294515/29334428-badcdc2a-81dd-11e7-85c3-b6b9c3d47175.png)

![1](https://user-images.githubusercontent.com/18294515/29334451-d1d2db32-81dd-11e7-9e0d-331f34ef3a0d.png)

- [ ] É possível tirar a parte indicada da ilustração do mapa?
![1](https://user-images.githubusercontent.com/18294515/29334483-e9bb8852-81dd-11e7-8fba-c8b348918fdb.png)

**Comment by miguelpeixe** [comment]
Os tamanhos foram atualizados e o grid redistribuído. Sobre as ilhas que aparecem no canto superior direito do mapa, não há como removê-los sem alterar a tecnologia de mapa utilizada. Sua aparição é relativa à resolução e com o novo grid (menos espaço no mapa) ele tem menos chances de aparecer.

**Comment by thaisrigolon** [comment]
Certo.
Issue homologada.
