### ISSUE TITLE
Layout - Página da secretaria

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#36]
- [x] Deixar o texto das estatísticas numa linha só:
![1](https://user-images.githubusercontent.com/18294515/28835738-ca5e7d6a-76bc-11e7-9995-ee94be9607f5.png)

- [x] Suavizar os pontilhados, puxando para o cinza:
![1](https://user-images.githubusercontent.com/18294515/28835685-9a2bc29c-76bc-11e7-896b-575f7bbac79a.png)

**Comment by thaisrigolon** [comment]
O link que temos para validar esta página é: http://portal-mapas.conexaobrasil.org/author/vgeorge/
Mas o texto das estatísticas não está numa linha só. Este link está atualizado ou devemos acessar outro?

**Comment by miguelpeixe** [comment]
Foi alterado o estilo para ter maior possibilidade de apresentação em uma linha só. Isso vai depender da resolução de tela. Como o texto é flexível e queremos otimizar legibilidade, para deixar em uma linha só será necessário ter um texto com menos caracteres.

**Comment by thaisrigolon** [comment]
Certo, vamos manter assim a princípio.
Issue homologada.
