### ISSUE TITLE
Layout - Página de Suporte

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#38]
- [x] Alterar frase de busque por tutoriais para "Busque informações de suporte"
![1](https://user-images.githubusercontent.com/18294515/28842864-ae87c664-76d5-11e7-97ef-9c504fdc8d9e.png)

- [x] Alterar "chat" para "Rocket Chat"
![1](https://user-images.githubusercontent.com/18294515/28842918-cfb97c9c-76d5-11e7-8262-386365cecc6f.png)

- [x] Separar melhor a parte de manual e de chat:
![1](https://user-images.githubusercontent.com/18294515/28842976-fcb42fd0-76d5-11e7-8c55-abb567723cdd.png)

- [x] Diminuir o título do manual:
![1](https://user-images.githubusercontent.com/18294515/28843057-33697012-76d6-11e7-9a63-f2a60a55a39e.png)

- [x] Adicionar título para os tutoriais:
![1](https://user-images.githubusercontent.com/18294515/28843005-1848b5e0-76d6-11e7-968c-0b0b531ccd7d.png)

- [x] Alterar o texto para:

> Mapas Culturais foi criado pelo **[Instituto TIM](http://institutotim.org.br/)** em parceria com a Secretaria de Cultura do Município de São Paulo, a primeira a adotar a plataforma, em 2014. Atualmente, a solução está em operação no Ministério da Cultura, em estados e municípios de todas as regiões do Brasil e até no exterior. Em 2015, Mapas Culturais passou a ser a plataforma oficial do Sistema Nacional de Informações e Indicadores Culturais (SNIIC), sendo o sistema oficial para mapeamento colaborativo e gestão da cultura do Ministério da Cultura.

![1](https://user-images.githubusercontent.com/18294515/28843152-89c2cd28-76d6-11e7-8360-85ea8952f600.png)

**Comment by thaisrigolon** [comment]
- [x] O título "tutoriais" deve seguir o mesmo padrão de manual:
![1](https://user-images.githubusercontent.com/18294515/29334259-30fdfa2a-81dd-11e7-96ee-7f9a37334b30.png)
![2](https://user-images.githubusercontent.com/18294515/29334260-33b8dad2-81dd-11e7-9164-939291a863ed.png)

**Comment by miguelpeixe** [comment]
Feito

**Comment by thaisrigolon** [comment]
Ok, homologado.
