### ISSUE TITLE
Wireframe - Mapa de Instalações

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#4]

**Comment by thaisrigolon** [comment]
- [x] Alterar o título "Instalações pelo Brasil" para: "Mapa das Instalações"

- [x] Os números precisam de separador:
![1](https://cloud.githubusercontent.com/assets/18294515/24171404/1d4f48aa-0e63-11e7-9fcf-2268b19ece53.png)

- [x] Tirar essa parte dessa página:
![1](https://cloud.githubusercontent.com/assets/18294515/24171541/b6e63000-0e63-11e7-8589-e71971d4cd76.png)

- [x] Alterar a nomenclatura de "Blog dos gestores" para "Blog da Rede"

- [x] Essa parte do blog da rede colocar no local onde está a parte "Faça parte da comunidade":
![1](https://cloud.githubusercontent.com/assets/18294515/24173294/4429b968-0e6a-11e7-8b4a-c75b332d44d5.png)

- [x] Os dados das outras instalações poderia ocupar o espaço que a parte de blog dos gestores está ocupando e pode diminuir um pouco o nome das secretarias.
![1](https://cloud.githubusercontent.com/assets/18294515/24173384/911ec010-0e6a-11e7-806c-221bfeb0475d.png)

**Comment by miguelpeixe** [comment]
Atualizações realizadas, além disso incluí na página uma área de widgets dinâmicos ao lado do blog dos gestores.

http://dev.aparabolica.com.br/mapasculturais/wireframe/html/installations.html

d1dc6b8ba429f1f5640c6f2b04600808be297515

**Comment by thaisrigolon** [comment]
Ok.
