### ISSUE TITLE
Integração de menus

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#40]

**Comment by vgeorge** [comment]
O estilo está quebrado:

<img width="1057" alt="captura de tela 2018-01-27 as 12 13 56" src="https://user-images.githubusercontent.com/329694/35471858-9cc8d4dc-035b-11e8-9ddb-c2513680ff1a.png">

**Comment by cabelotaina** [comment]
Me menda uma copia do código gerado para o menu. Para comparar com a que tenho sendo gerada aqui. Assim posso ter uma ideia do que não esta funcionando. Atualmente o css não teve modificações para a implementação desta funcionalidade. Note que o código esta em header e basicamente se trata disso:

```php
          wp_nav_menu(array(
            "theme_location" => "header",
            "menu_class" => "",
            "menu_id" => "",
            "container_class" => "u-pull-right",
            "container_id" => "mastnav"
            )
          );
```

**Comment by vgeorge** [comment]
O menu aparece corretamente para você? Esse é o código que está sendo gerado:

<img width="592" alt="captura de tela 2018-01-27 as 13 25 54" src="https://user-images.githubusercontent.com/329694/35472366-a8008886-0365-11e8-8877-27c43e26004a.png">

**Comment by cabelotaina** [comment]
Sim ele aparece, e esta com o código bem diferente:

![image](https://user-images.githubusercontent.com/1827173/35472415-e6c93442-0355-11e8-885f-74de245a92e8.png)

**Comment by cabelotaina** [comment]
Nesse caso o css não esta quebrado ele nem mesmo foi aplicado sobre a tag.

**Comment by vgeorge** [comment]
Agora os menus estão aparecendo corretamente

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
