### ISSUE TITLE
Listagem de blog da rede na página inicial

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#43]

**Comment by vgeorge** [comment]
Não está sendo exibido o nome do usuário e avatar. Quando o usuário não tiver avatar seria melhor exibir uma imagem genérica, por exemplo o logo da plataforma.

**Comment by cabelotaina** [comment]
![image](https://user-images.githubusercontent.com/1827173/36793625-a26337d6-1c7c-11e8-9250-52bf3a057627.png)

Parece que esta ok isso

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
