### ISSUE TITLE
Botões da seção "Faça parte da comunidade"

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#44]
Integrar:
 - [x] GitHub
 - [x] Participe da discussão

Provavelmente deverá ser necessário criar as opções de edição desse campo numa página configuração à parte (geralmente uma única página de "opções do tema").

**Comment by vgeorge** [comment]
O botão do Github está funcionando corretamente, mas o "Participe da discussão" deve apontar à página interna do delibera e não a um link absoluto.

**Comment by cabelotaina** [comment]
feito

**Comment by vgeorge** [comment]
Onde é possível configurar estes links? @cabelotaina

**Comment by vgeorge** [comment]
Funcionalidade continua com problema. cc @cabelotaina

**Comment by cabelotaina** [comment]
A pagina interna do delibera eh a pagina comunidade?

Para editar o link do github

![image](https://user-images.githubusercontent.com/1827173/37690717-a7999dde-2c8b-11e8-8b30-444991d9e58c.png)

![image](https://user-images.githubusercontent.com/1827173/37690730-bca435b8-2c8b-11e8-8f36-c7242f8b59cb.png)

![image](https://user-images.githubusercontent.com/1827173/37690742-ced09dd0-2c8b-11e8-874e-9e632f588375.png)

**Comment by vgeorge** [comment]
O link foi alterado como você instruiu, mas o resultado continua o mesmo.

O link para a página da comunidade é o endereço `/comunidade`, que é a página do delibera.

**Comment by cabelotaina** [comment]
Ola desculpem o vacilo, dei uma olhada e vi que estava indo para localhost na forma que fiz. Fiz uma correção deixando hardcoded, o github já estava corrigido desde a primeira vejam se a versão de homologação esta de acordo com a versão de to-validate.

**Comment by vgeorge** [comment]
@miguelpeixe O logo do github está desalinhado e apontando para a página de suporte, e não para o Github.

**Comment by miguelpeixe** [comment]
URL corrigida, aqui nao aparece desalinhado, segue:
![Captura de tela de 2018-05-30 15-57-04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ceae1f82b317f7d9acf500/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2733dd5b665ec123b505a424bab5c585b56e0ebc969f9ec6923ce4e01ffd4650c7dc56c12abec801fb707b9208b4c8dbfbfd949c6ef2f39f5c9de116a415841c3aa1f27aa8b4ac152f74ee34a52a4153066e575367955d9.png)

**Comment by Nathlis** [comment]
Aprovado.
