### ISSUE TITLE
Integração newsletter

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#45]
Mailchimp?

**Comment by vgeorge** [comment]
Instalei o plugin do Mailchimp e coloquei a API, mas o form não apareceu:

<img width="1009" alt="captura de tela 2018-01-27 as 12 51 59" src="https://user-images.githubusercontent.com/329694/35472113-02810c40-0361-11e8-9a59-d037bc3800a8.png">

**Comment by cabelotaina** [comment]
Primeiro

![image](https://user-images.githubusercontent.com/1827173/35472382-56346b36-0355-11e8-931d-1aaae0bae089.png)

Segundo

![image](https://user-images.githubusercontent.com/1827173/35472384-5ec20cb8-0355-11e8-89db-598e868a23c1.png)

Texto para o campo

```html
<div class="newsletter-form">
  <h2>
    <span class="fa fa-envelope"></span>
    Newsletter
  </h2>
  <input type="email" name="EMAIL" placeholder="Preencha seu email" required />
  <input type="submit" value="Cadastrar" />
</div>
```

**Comment by vgeorge** [comment]
Existe algum outro passo? Na instalação de homologação aparece um erro ao invés do formulário.

**Comment by vgeorge** [comment]
Consegui resolver, mas ele está retornando a mensagem de sucesso/erro em inglês, mesmo quando a instalação do WP está em português.

**Comment by cabelotaina** [comment]
isso deve estar relacionado ao plugin temos que ver se ele possui tradução para o portugues

**Comment by cabelotaina** [comment]
Pessoal fiz um teste com ele modificando o arquivo de po e mo do portugues e nao funciona. Nao sei como modificar sem ser dessa forma. Alguma sugetao @miguelpeixe @vgeorge

**Comment by vgeorge** [comment]
Segundo os docs a gente tem que usar esse plugin também:

https://wordpress.org/plugins/mc4wp-wpml/

Mas instalei e não acontece nada.

**Comment by cabelotaina** [comment]
temos que instalar o wpml https://wpml.org/pt-br/ pois ele deve ser uma extenção dele. O wpml permite fazer tradução de plugins temas e sites em wp. A redelivre usa ele.

**Comment by vgeorge** [comment]
Este WPML é fechado, não é? Será possível que a mensagem seja traduzida de outra maneira, talvez por um callback do Mailchimp?

**Comment by cabelotaina** [comment]
As mensagens podem ser modificadas em:

![image](https://user-images.githubusercontent.com/1827173/37692418-2bef13a6-2c97-11e8-9f59-6b5a83a196df.png)

![image](https://user-images.githubusercontent.com/1827173/37692428-3a526178-2c97-11e8-9347-989bf14815e4.png)

**Comment by vgeorge** [comment]
@thaisrigolon o newsletter está configurado. Para traduzir as mensagens, acesse aqui:

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/admin.php?page=mailchimp-for-wp-forms&view=edit-form&form_id=47&tab=messages

**Comment by thaisrigolon** [comment]
Ok, já conseguimos alterar o texto.

Como configurar para a nossa newsletter oficial do mailchimp? Testamos por aqui e ainda não está integrada.

**Comment by vgeorge** [comment]
É preciso colocar a chave de API da conta do Mailchimp do Mapas Culturais nesta página:

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/admin.php?page=mailchimp-for-wp

**Comment by Nathlis** [comment]
Homologado.
