### ISSUE TITLE
Integração de corpo de texto da página Mapa da Rede

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#47]

**Comment by cabelotaina** [comment]
@vgeorge explica qual seria a tarefa aqui, como se daria essa integração...

**Comment by vgeorge** [comment]
Aqui falta adicionar um campo para editar a caixa em amarelo, como foi feito em outros templates.

**Comment by Nathlis** [comment]
Homologada.
