### ISSUE TITLE
Integração das estatísticas de instalações na página Mapa da Rede

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#48]

**Comment by vgeorge** [comment]
Os dados consolidados estão sendo exibidos corretamente:

http://hmg.mapasculturais.medialab.ufg.br/rede/

**Comment by thaisrigolon** [comment]
Como será a consulta dos números das plataformas para apresentação dos indicadores? Será atualizado com qual periodicidade?

**Comment by vgeorge** [comment]
É feita uma rotina que busca todo histórico de agentes, eventos, espaços e projetos para cada instalação cadastrada no portal. No momento ela sendo executada a cada 15 minutos, mas são muitos requests nas API e me parece melhor atualizar os dados uma vez por dia.

**Comment by HeloMubarack** [comment]
Como nós fazemos para cadastrar uma instalação? Poderia dar um exemplo? Assim podemos cadastrar um e fazer testes para ver se a atualização de uma vez por dia estará funcionando.

**Comment by vgeorge** [comment]
Existem 13 instâncias cadastradas na homologação, vocês podem ver neste link:

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/users.php?role=instance

As instalações são cadastradas pela adição de um usuário com a função "Instância", como neste exemplo do jpcultura:

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/user-edit.php?user_id=5

Para que as estatísticas possam ser obtidas é preciso que o campo "URL da Instância" esteja apontando para a raiz da API, que é geralmente a própria URL do site. No caso de JP está `http://jpcultura.joaopessoa.pb.gov.br`.

Nesta mesma página é possível também cadastrar os membros da equipe que vão aparecer na página da instância, bem como as coordenadas e outros links.

Eu tinha adicionado antes o spcultura que estava mais completa que a de JP, mas parece foi removida.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
