### ISSUE TITLE
Integração dos dados de mapa na página Mapa da Rede

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#49]
http://hmg.mapasculturais.medialab.ufg.br/rede

**Comment by vgeorge** [comment]
- [x] Os botões do zoom do mapa estão quebrados
- [x] O botão "ver perfil" está apontando para o link externo da instância, deveria apontar para o perfil da instância no portal.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
