### ISSUE TITLE
Wireframe - Perfil da Instalação

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#5]

**Comment by thaisrigolon** [comment]
- [x] No título adicionar o nome da instalação também. Exemplo:
![803735970_71613](https://cloud.githubusercontent.com/assets/18294515/24173513/2476d56e-0e6b-11e7-8e0c-2a4b013b6489.jpg)

- [x] Seria legal se o usuário pudesse alterar os indicadores desse gráfico (número de agentes, eventos, espaços e projetos)
![1](https://cloud.githubusercontent.com/assets/18294515/24173577/51d1cbcc-0e6b-11e7-9b42-557b9af3ff60.png)

- [x] Na parte de equipe ter possibilidade de colocar foto de cada colaborador.
![1](https://cloud.githubusercontent.com/assets/18294515/24173616/83fbf974-0e6b-11e7-9608-52cc0908e08f.png)

- [x] Ter uma parte para contato com informações da secretaria
![1](https://cloud.githubusercontent.com/assets/18294515/24173655/ac0df7e6-0e6b-11e7-8612-b932da1f02d2.png)

- [x] Ter paginação e não deixar com rolagem longa...
![1](https://cloud.githubusercontent.com/assets/18294515/24173711/ea92a7a0-0e6b-11e7-911f-a545fc477bac.png)

- [x] Tirar essa parte dessa página:
![1](https://cloud.githubusercontent.com/assets/18294515/24171541/b6e63000-0e63-11e7-8589-e71971d4cd76.png)

**Comment by miguelpeixe** [comment]
Ok

http://dev.aparabolica.com.br/mapasculturais/wireframe/html/profile.html

b247122ce1173b44789ad515b25cdf12ee6e4d03

**Comment by thaisrigolon** [comment]
Tudo ok. Só os números que também precisam de separador, como está na página do mapa das instalações:

![1](https://cloud.githubusercontent.com/assets/18294515/24264032/dc0e0eea-0fdd-11e7-979d-f5d375daf4d5.png)

**Comment by miguelpeixe** [comment]
ok 2c7f646abcd8287f6e8765773b9f2c49fad07c25
