### ISSUE TITLE
Criação de campos para edição da página Suporte

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#50]
- [x] Link para Rocket.Chat
 - [x] Upload/link do manual (pdf)

**Comment by cabelotaina** [comment]
Coloquei apenas um campo de link, pois basta subir o arquivo em media e copiar a url.

**Comment by vgeorge** [comment]
A implementação deste campo deve ser feita via ACF, como foi feito na homepage, pois assim se mantém um padrão de configuração de páginas e evita-se a má formatação da página de configuração do tema. O campo pode ser gerado via ACF e exportado para o PHP, como foi feito para a homepage no arquivo `inc/homepage-config.php`.

**Comment by cabelotaina** [comment]
cara essa foi, fiz do mesmo jeito:

http://localhost:8080/wp-admin/post.php?post=20&action=edit
http://hmg.mapasculturais.medialab.ufg.br/suporte/

**Comment by vgeorge** [comment]
Não, entendi. O que foi feito?

**Comment by vgeorge** [comment]
Legal, vi que agora a configuração está na página do template de suporte. Mas ainda falta fazer o i18n desta desta página (`inc/support-config.php`), pois estão aparecendo textos em inglês.

Link direto: http://hmg.mapasculturais.medialab.ufg.br/wp-admin/post.php?post=20&action=edit

**Comment by cabelotaina** [comment]
estou subindo o material com os campos definidos para tradução e logo vou subir a nova tradução tb. Favor colocar para revisão.

**Comment by cabelotaina** [comment]
pronto resolvida essa issue

**Comment by thaisrigolon** [comment]
- [x] Como adicionamos o link dos tutoriais? Não tem esse campo no painel...
![1](https://user-images.githubusercontent.com/18294515/37344908-7319b436-26aa-11e8-9237-e8d003ebfe64.png)


- [x] Os links precisam abrir numa nova aba
![1](https://user-images.githubusercontent.com/18294515/37344985-a1f4b17a-26aa-11e8-9866-90afb606a4e5.png)
![2](https://user-images.githubusercontent.com/18294515/37344987-a21db52a-26aa-11e8-9ed3-7c87b973ff25.png)
![3](https://user-images.githubusercontent.com/18294515/37344988-a24443ac-26aa-11e8-8746-b6474481886a.png)

- [x] O link do manual foi inserido, mas não abre após clicar nos botões:
![1](https://user-images.githubusercontent.com/18294515/37345028-b7e31396-26aa-11e8-8b37-439e6756df73.png)

![2](https://user-images.githubusercontent.com/18294515/37345030-bb048230-26aa-11e8-8c99-8b84de70f065.png)

![1](https://user-images.githubusercontent.com/18294515/37345046-c4257324-26aa-11e8-81e5-e363585e5687.png)

- [x] No protótipo, a complexidade tinha sido definida como "baixa" / "média" / "alta". No ambiente de homologação está como 1, 2 e 3:

- Protótipo:
![1](https://user-images.githubusercontent.com/18294515/37345136-008ba98c-26ab-11e8-97c6-9cdef3e588aa.png)

- Homologação:
![1](https://user-images.githubusercontent.com/18294515/37345118-f2ded84a-26aa-11e8-9cdf-d951d4d8c485.png)

**Comment by cabelotaina** [comment]
@thaisrigolon - quanto aos valores de complexidade modifique um tutorial para outro valor e salve novamente veja se muda, pois isso tem a ver com os testes anteriores que foram feitos e banco fica um pouco sujo e pode causar essa confusão. veja se não é isso.

**Comment by thaisrigolon** [comment]
Não estou conseguindo testar. Clico para adicionar novo tutorial e a seguinte página aparece:

![1](https://user-images.githubusercontent.com/18294515/37727814-83b98f0a-2d17-11e8-9c97-de045b03901d.png)

**Comment by vgeorge** [comment]
A homologação voltou ao ar agora.

**Comment by thaisrigolon** [comment]
- [ ] No caso os grupos são: gestores ou desenvolvedores. Dá pra ter uma opção para gestores E desenvolvedores? Podemos adicionar mais grupos?
![1](https://user-images.githubusercontent.com/18294515/37730740-34f80196-2d1f-11e8-9dfb-21f4c2fd2e71.png)

- [x] Tem como deixar esse filtro menor? Está muito grande.
![1](https://user-images.githubusercontent.com/18294515/37730827-69c7327a-2d1f-11e8-898a-e1c6b69e389f.png)

**Comment by vgeorge** [comment]
Não é possível usar o operador "E" neste caso. Agora é preciso uma revisão do @miguelpeixe para arrumar o filtro.

**Comment by Nathlis** [comment]
- [ ] Não ficou claro se é possível adicionar mais grupos além de "gestores" e "desenvolvedores". Se sim, onde incluímos?

![image](https://user-images.githubusercontent.com/18741130/39543301-25907440-4e21-11e8-9495-bad22d72c026.png)

- [ ] O filtro não está funcionando, após selecionar alguma opção ele não filtra e não é possível mudar o filtro (fica travado)

![sem titulo](https://user-images.githubusercontent.com/18741130/39544004-2426a99c-4e23-11e8-94b4-ade605db055c.jpg)

![portal do mapas culturais](https://user-images.githubusercontent.com/18741130/39544063-5340f700-4e23-11e8-91a6-f0f9e05265f2.png)

**Comment by Nathlis** [comment]
- [ ] Botão de "Veja mais tutoriais" não funciona:

![portal do mapas culturais 1](https://user-images.githubusercontent.com/18741130/39544183-a43d0da6-4e23-11e8-86d5-d7b80fa753eb.png)

**Comment by vgeorge** [comment]
Natalia, sobre os pontos:

1. não é possível criar novos grupos;
2. confirmo o bug do seletor;
3. link para botão resolvido.

Então, aqui o que falta para esta issue é consertar o seletor de grupo de tutoriais, ok?

**Comment by Nathlis** [comment]
O filtro ainda não funciona

**Comment by Nathlis** [comment]
Aprovado.
