### ISSUE TITLE
Integração de funcionalidades da página Suporte

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#51]
- [x] Corpo de texto e demais metadados (links)
 - [x] Seção tutoriais
 - [x] Ferramenta de busca de tutoriais

**Comment by vgeorge** [comment]
http://hmg.mapasculturais.medialab.ufg.br/suporte/

Links estão funcionando, mas seção de tutoriais está com problemas de formatação. Sugiro consultar esta página para entender como as classes css estão sendo aplicadas:

http://portal-mapas.conexaobrasil.org/tutorials/

**Comment by cabelotaina** [comment]
Ola me parecem iguais as paginas, veja se o problema persiste com essa atualização se o problema ainda existir, por favor faz um print e cole aqui.

**Comment by vgeorge** [comment]
Exibição correta da lista de tutoriais:

<img width="653" alt="captura de tela 2018-02-24 as 11 27 44" src="https://user-images.githubusercontent.com/329694/36629962-f9da7788-1955-11e8-8611-4f0b6fbd097a.png">

Como está agora:

<img width="635" alt="captura de tela 2018-02-24 as 11 31 02" src="https://user-images.githubusercontent.com/329694/36629971-3db53132-1956-11e8-9c07-da788ed83929.png">

O que é necessário corrigir:

- [x] O título do tutorial está sublinhado e em azul, aplicar formatação correta;
- [x] O link para a categoria está sublinhado;
- [x] A complexidade está com erro, exibe um código e não o termo;
- [x] Na lista devem ser exibido apenas o excerto e não todo o conteúdo;
- [x] O tamanho da fonte deve ser maior, como formatado na homologação antiga.

**Comment by cabelotaina** [comment]
Acredito que esta ok

**Comment by vgeorge** [comment]
Complexidade segue aparecendo como um código e o link do botão está quebrado, deve apontar para `/tutoriais`. 

O estilo e corpo do texto estão incorretos, eu posso ajudar depois.

**Comment by vgeorge** [comment]
Aqui só falta arrumar o campo complexidade, que está aparecendo como um número inteiro:

http://hmg.mapasculturais.medialab.ufg.br/suporte/

**Comment by cabelotaina** [comment]
Feito, agora eh necessário atualizar na hml

**Comment by Nathlis** [comment]
Aprovado
