### ISSUE TITLE
Integração do cabeçalho (Página Autor)

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#52]
- [x] Corpo de texto
- [x] Estatísticas
- [x] Botão "Acesse a Plataforma"

**Comment by vgeorge** [comment]
A validar:

http://hmg.mapasculturais.medialab.ufg.br/author/spcultura/

**Comment by thaisrigolon** [comment]
Está ok. A única alteração necessária é abrir outra aba quando o usuário clicar no botão "acesse a plataforma":

![1](https://user-images.githubusercontent.com/18294515/37093945-eea9936a-21ef-11e8-8f2d-a875bc8a68f3.png)

**Comment by vgeorge** [comment]
Foi feita a modificação do botão.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
