### ISSUE TITLE
Listagem de posts (Página Autor)

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#53]

**Comment by vgeorge** [comment]
Referência: #27

Formatação está incorreta: 
http://hmg.mapasculturais.medialab.ufg.br/author/spcultura/

**Comment by cabelotaina** [comment]
ola parece que esta ok isso:

http://portal-mapas.conexaobrasil.org/author/vgeorge/

http://hmg.mapasculturais.medialab.ufg.br/author/spcultura/

**Comment by miguelpeixe** [comment]
Me parece que deve ser utilizado excerpt e não content para listas. O date também só aparece para o primeiro resultado, o método de exibição da data deve ser alterado de `the_date()` para `echo get_the_date()` (ref: https://codex.wordpress.org/Function_Reference/the_date)

**Comment by vgeorge** [comment]
Feito:

http://hmg.mapasculturais.medialab.ufg.br/author/spcultura/

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
