### ISSUE TITLE
Funcionalidades da barra lateral (Página da Instância)

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#54]
- [x] Estatísticas
- [x] Equipe
- [x] Metadados

**Comment by vgeorge** [comment]
Tomando como exemplo: 

http://hmg.mapasculturais.medialab.ufg.br/author/spcultura/

- [x] As estatísticas não estão sendo exibidas;
- [x] Link para o twitter não está aparecendo;

**Comment by vgeorge** [comment]
A resolver:

- [ ] Estilo da seta do dropdown deve seguir #36 
- [x] Quando o dropdown é alterado a largura do gráfico não é reajustada e ele extrapola a página
- [x] O texto abaixo do gráfico está mostrando o valor total de usuários e não os dos últimos 30 dias

**Comment by vgeorge** [comment]
Falta resolver o estilo da seta. cc @miguelpeixe

**Comment by miguelpeixe** [comment]
Não entendi a questão do estilo da seta

**Comment by vgeorge** [comment]
O dropdown abaixo não está de acordo com o #36:

![captura de tela 2018-04-19 as 10 33 06](https://user-images.githubusercontent.com/329694/38994620-434ef9fc-43bd-11e8-9d16-8784b043ddd7.png)

Aqui está o link da página onde ele aparece:

http://hmg.mapasculturais.medialab.ufg.br/author/spcultura/

**Comment by miguelpeixe** [comment]
Isso é uma variação de browser, cada browser vai exibir o seu padrão.

**Comment by miguelpeixe** [comment]
![Screen Shot 2018-05-28 at 19.35.16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ceae1f82b317f7d9acf500/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456fb6b7191a379e60c2854415e48be5d4a1f06a3a3dc78e2a436628f5458e4d23c5c73923f11a4be811fbf02b229881c80b0bb9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5ff34fe74457ac173164f43b.png)

Segue exemplo no chrome

**Comment by Nathlis** [comment]
Aprovado
