### ISSUE TITLE
Funcionalidades da página comunidade

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#55]
- [x] Estatísticas do repositório GitHub
 - [x] Corpo do trecho "Discussões"
 - [x] Lista/links categorias de pauta
 - [x] Área de autenticação/informações de usuário autenticado (login/logout)

**Comment by cabelotaina** [comment]
Aqui sera utilizado tema ao invez de categoria, porque a categoria de pauta é a mesma categoria de post, e por isso ao clicar na categoria somos enviados para uma pagina que lista nao apenas pautas mas posts tambem, no entanto o delibera tem uma categoria que se chama tema, que permite filtrar as pautas pelo tema, acredito que seja o melhor a usar. Outro ponto é que as pautas vão aparecer na listagem nas paginas de categorias de post, isso é um problema?

**Comment by cabelotaina** [comment]
@miguelpeixe por favor compartilha comigo aquela documentação que vai me ajudar com a construção de uma página de settings para o tema mais alinhada ao wp admin.

**Comment by vgeorge** [comment]
Aqui está um exemplo da página com estrutura:

http://portal-mapas.conexaobrasil.org/comunidade/

A página atual não está exibindo o grafico do Github:

http://hmg.mapasculturais.medialab.ufg.br/comunidade/

Em que situação está a integração com o Delibera?

**Comment by cabelotaina** [comment]
O grafico do github esta ok. 

A integração do delibera:

Temos a página de single pauta, archive e estou terminando o add pauta via front (tenho um bug, não detecta qual o estagio da pauta assim que insere a pauta via front), e falta a página de author, esta não possui template. (ela não vai existir?)

**Comment by vgeorge** [comment]
O gráfico do Github está ok na versão antiga, mas não está aparecendo na homologação atual:

<img width="888" alt="captura de tela 2018-02-24 as 11 16 09" src="https://user-images.githubusercontent.com/329694/36629862-6b67c434-1954-11e8-8916-3736ed74beb3.png">

**Comment by vgeorge** [comment]
Não haverá template de página dedicada a autores do delibera, o @miguelpeixe pode confirmar.

**Comment by vgeorge** [comment]
O gráfico está aparendo corretamente agora, provavelmente a versão antiga estava no cache.

**Comment by cabelotaina** [comment]
acredito que cobri tudo desta issue

**Comment by vgeorge** [comment]
Ainda falta a integração com o Delibera, que não está ativo na homologação. Coloquei vcs em cópia com o sysadmin para resolver isso, @miguelpeixe e @cabelotaina

**Comment by thaisrigolon** [comment]
@vgeorge a integração já está disponível para testes?

**- Dúvida**
As estatísticas do repositório do github estão atualizadas? Não parece que está batendo com os números do github: https://github.com/hacklabr/mapasculturais

![1](https://user-images.githubusercontent.com/18294515/37345504-eb630c8e-26ab-11e8-9a02-06e8d6d99e92.png)

![1](https://user-images.githubusercontent.com/18294515/37345529-f76731a4-26ab-11e8-855a-4a2d9546872a.png)

**Comment by vgeorge** [comment]
Por favor, revisar a integração, @cabelotaina.

**Comment by thaisrigolon** [comment]
- [x] Também corrigir o deslocamento de sombras do texto:
![1](https://user-images.githubusercontent.com/18294515/37527896-e7d21cd2-2911-11e8-9eea-590472ed6453.png)

**Comment by vgeorge** [comment]
@thaisrigolon abri uma issue em separado para as sombras: https://github.com/institutotim/wp-theme-mapasculturais/issues/93

@cabelotaina a integração já foi revisada?

**Comment by cabelotaina** [comment]
As sombras estão ok, e o problema eh que o pessoal do hacklab usa um repo que não eh o master como principal, estavamos pegando informações do repositorio master e eles usam develop, troquei para develop para que haja coincidência de resultados.

**Comment by thaisrigolon** [comment]
Beleza. Mas foi atualizado o código? Porque os números ainda permanecem os mesmos.

**Comment by cabelotaina** [comment]
Sim esta batendo com o repo em develop, http://hmg.mapasculturais.medialab.ufg.br/comunidade/, faça refresh com shit+ctrl+F6

**Comment by Nathlis** [comment]
Pessoal desculpa, não sei se entendi direito, mas pra mim os números ainda não batem:

![1](https://user-images.githubusercontent.com/18741130/39584526-0a04fba8-4ec9-11e8-95b7-c758ca3fb59d.png)


![2](https://user-images.githubusercontent.com/18741130/39584535-0d71b916-4ec9-11e8-885f-f892fc07a44f.png)

**Comment by vgeorge** [comment]
Natalia, para evitar que seja feito request a cada vez que a página é aberta, existe um cache de 3 horas para atualização dos dados. Provavelmente alguém acessou esta página no momento em que a contagem estava em 5.573, houve novos commits no repositório e você acessou menos de 3 horas depois. Para mim, agora a contagem está correta, em 5597.

**Comment by Nathlis** [comment]
Entendi, obrigada. Homologada.
