### ISSUE TITLE
Página única da pauta (delibera)

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#56]

**Comment by vgeorge** [comment]
O ambiente de homologação não está com o Delibera ativado para validação.

**Comment by cabelotaina** [comment]
por favor vejam se é possivel instalar neste final de semana.

**Comment by vgeorge** [comment]
O Delibera está disponível na homologação.

**Comment by vgeorge** [comment]
Link para página de criação de pauta:

http://hmg.mapasculturais.medialab.ufg.br/adicionar-pauta/

**Comment by thaisrigolon** [comment]
- [x] Alterar título para: **Novo tópico de discussão**
![4](https://user-images.githubusercontent.com/18294515/37794765-49558e74-2df1-11e8-99f8-f7c4fe831f3b.png)


- [x] Como definimos os temas disponíveis?
![3](https://user-images.githubusercontent.com/18294515/37794743-312cbb06-2df1-11e8-8dd1-9144f93a8c21.png)

- [x] Na página da discussão os botões estão desconfigurados:
![1](https://user-images.githubusercontent.com/18294515/37794822-70bb3ef0-2df1-11e8-8926-42873b3cd8fc.png)

- [ ] É possível alterar as cores de fundo do comentário? Seria bom que as cores dialogassem com o layout do portal.
![2](https://user-images.githubusercontent.com/18294515/37794830-77ef59ae-2df1-11e8-9cb1-884d64a90e59.png)

- [x] Alterar nomenclatura para "Tópicos em discussão"
![1](https://user-images.githubusercontent.com/18294515/37794888-a08c73ec-2df1-11e8-8ef7-4ed4bf5669f5.png)

- [x] Alterar nomenclatura para "Tópicos em discussão"
![1](https://user-images.githubusercontent.com/18294515/37794923-bfdbf6d2-2df1-11e8-8346-466eb3a51527.png)

- [x] É possível adicionar um botão de busca por tópicos?
![1](https://user-images.githubusercontent.com/18294515/37794946-cf381ade-2df1-11e8-8424-16a431cb7c6a.png)

- [x] Alinhar discussões com tópicos em discussão
![1](https://user-images.githubusercontent.com/18294515/37795007-f61c3bda-2df1-11e8-9505-9883ce0e43e4.png)

- [ ] É possível deixar essa parte esquerda apenas para o título e um texto que vai explicar essa funcionalidade de tópicos?
![1](https://user-images.githubusercontent.com/18294515/37795081-2f50e34c-2df2-11e8-8985-802464604838.png)


- [x] Alterar título para "Estágio da discussão"
![1](https://user-images.githubusercontent.com/18294515/37795047-1467b9ca-2df2-11e8-9db3-7c6ef7fc673c.png)

**Comment by miguelpeixe** [comment]
Os temas de pauta podem ser definidos através do painel de controle, em:  Pautas -> Temas

Não entendi a questão sobre a parte esquerda da página, onde é exibido o título, filtro por temas e botão para criação de novo tópico (pauta). Não existirá esse filtro?

**Comment by Nathlis** [comment]
- [x] Está dando um erro no Aceitar e Rejeitar a pauta, essa pauta foi criada direto no WordPress:

![portal do mapas culturais](https://user-images.githubusercontent.com/18741130/39579232-9820b63c-4ebc-11e8-8d65-27c520ebcffd.png)

- [x] Quando se cria uma pauta diretamente pela plataforma, não aparece o REJEITAR:

![portal do mapas culturais 2](https://user-images.githubusercontent.com/18741130/39579705-c820bc82-4ebd-11e8-8149-918014ac0350.png)

![portal do mapas culturais 1](https://user-images.githubusercontent.com/18741130/39579713-cf1083b0-4ebd-11e8-9dc0-8570bfb9f10f.png)

- [x] Esses títulos deveriam ser links para a página http://hmg.mapasculturais.medialab.ufg.br/pauta/ 

![links](https://user-images.githubusercontent.com/18741130/39581626-635a0858-4ec2-11e8-944b-9086d524b5fb.png)


- [x] Nessa página http://hmg.mapasculturais.medialab.ufg.br/pauta/ deveria ter a divisão dos títulos, e não deixar tudo listado sem ordem.. é possível? 

- [x] Dúvida, quando tiver muitas pautas terá tabulação de página?

**Comment by miguelpeixe** [comment]
Devido a problemas com o sistema de permissões no Delibera, achamos que será mais conveniente para o projeto pular a etapa de validação e assumir que todas as propostas de discussão já estejam qualificadas para a etapa de "Discussão".

**Comment by miguelpeixe** [comment]
Foram implementados os links nos títulos para a área de discussões filtrada pela "situação".  Para facilitar essa navegação, foi adicionado por padrão na barra lateral do arquivo de discussões uma navegação incluindo busca textual, temas e situação.

![Captura de tela de 2018-06-22 14-03-48.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ceae1f82b317f7d9acf500/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2733dd5b565ed103b505b424eaf5c5c5756e0ebc969f9ec6923ce4e01ffd4650c7dc56c12abec801fb707b9208b4c8dbfbfd949c6ef2f39f5c9de116a415841c3aa1f27aa8b4ac152f74ee34453ac143660e270327d55d9.png)

Para melhor integração na interface do site, o estilo nativo do Delibera foi atualizado para que os encaminhamentos tenham o padrão de cor amarelo, recorrente na interface do site

![Captura de tela de 2018-06-22 14-05-03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ceae1f82b317f7d9acf500/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2733dd5b565ed103b505b424ea95c585c56e0ebc969f9ec6923ce4e01ffd4650c7dc56c12abec801fb707b9208b4c8dbfbfd949c6ef2f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee34453ac143762e670367955d9.png)

**Comment by miguelpeixe** [comment]
Caso o número de discussões na página de arquivo exceda o limite estabelecido, a paginação estará disponível na interface.

**Comment by Nathlis** [comment]
Aprovado.
