### ISSUE TITLE
Páginas de posts

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#58]
## Conteúdo

 - Home de posts
 - Tags
 - Categorias
 - Busca
 - Termos de taxonomias customizadas
 - Arquivo por data (dia, mês, ano)

---

 - [x] Integrar cabeçalho
   - [x] Título e descrição (home de notícias ou título e descrição da categoria)
   - [x] Lista de categorias
 - [x] Integração de sidebar na barra lateral
 - [x] Lista de posts com thumbnail e paginação

**Comment by vgeorge** [comment]
- [x] Mostrar nome do usuário e não o de login
- [x] Seguir estilo do #14 
- [x] Widget de texto quebrado

**Comment by cabelotaina** [comment]
Mostrar nome de usuário e não o de login tem uma resposta em https://github.com/institutotim/wp-theme-mapasculturais/issues/59#issuecomment-360992798

**Comment by cabelotaina** [comment]
Vamos ter que fazer uma reunião para olhar especificamente para estas questões. Pois preciso conseguir reproduzir o erro.

**Comment by vgeorge** [comment]
Aqui está um exemplo com a formatação e estrutura esperada:

http://portal-mapas.conexaobrasil.org/2017/

O atual está assim:

http://hmg.mapasculturais.medialab.ufg.br/2018/

**Comment by vgeorge** [comment]
Fiz a formatação dos posts e estou trabalhando no widget.

@miguelpeixe não consegui resolver o redimensionamento da imagem, pode ajudar?

**Comment by vgeorge** [comment]
Link para validação: 

http://hmg.mapasculturais.medialab.ufg.br/noticias/

**Comment by thaisrigolon** [comment]
Adicionei um novo post e criei algumas categorias. Não selecionei as categorias 1, 2, e 3 e elas aparecem mesmo assim. Como removê-las?

![1](https://user-images.githubusercontent.com/18294515/37347610-fb0f9d96-26b0-11e8-8261-7404d0ecbe74.png)

![1](https://user-images.githubusercontent.com/18294515/37347676-256d0a4c-26b1-11e8-9c25-a342479bcccf.png)


Post: http://hmg.mapasculturais.medialab.ufg.br/2018/03/13/gestores-e-desenvolvedores-de-mapas-se-reunem/

**Comment by vgeorge** [comment]
Parece que o widget está exibindo todas categorias ao invés das selecionadas. @cabelotaina

**Comment by cabelotaina** [comment]
Eu expliquei o funcionamento disso na issue #59

**Comment by thaisrigolon** [comment]
Ok, @cabelotaina entendi. No entanto, todas as categorias estão aparecendo em todos os posts. E precisa aparecer somente as selecionadas. Como configuramos isso?

**Comment by vgeorge** [comment]
@thaisrigolon Aqui o comportamento é mostrar todas as categorias, mas na página única deve-se mostrar só as categorias associadas mesmo.

**Comment by thaisrigolon** [comment]
Ok, então esta issue está homologada.
