### ISSUE TITLE
Página única de post

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#59]
- [x] Cabeçalho
   - [x] Link para home de notícias
   - [x] Categoria(s) do post
   - [x] Título
 -  [x] Metadados (autor, data, tags)
 -  [x] Integração de sidebar na barra lateral

**Comment by vgeorge** [comment]
- [x] Mostrar nome do usuário e não o de login
- [ ] Seguir estilo do #14 
- [ ] Widget de texto quebrado

**Comment by cabelotaina** [comment]
Ola eu usei a func the_author para mostrar, ela permite que o usuário escolha qual nome mostrar. Se eu forçar e o usuário não tiver inserido o nome vamos ter que fazer um tratamento que na vdd é justamente o que a função faz

![image](https://user-images.githubusercontent.com/1827173/35473382-e3e5f920-0366-11e8-8243-d9f3e7169068.png)

https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/author-template.php#L23

Se vc olhar o the_author > get_the_author > $user.display_name

sendo que aqui vc vai ver o que display name mostra o nome amigavel do usuário

https://codex.wordpress.org/Function_Reference/get_currentuserinfo

acho que esta certo

**Comment by cabelotaina** [comment]
@vgeorge vc pode me mandar um print codigo do widget de texto quebrado ou alguma informação pois como eu disse não esta quebrando css ou qualquer coisa do tipo no momento. Por isso vou precisar de mais detalhes.

**Comment by vgeorge** [comment]
Exemplo:

http://hmg.mapasculturais.medialab.ufg.br/2018/02/22/dolore-enim-quis-est-proident/

Widget não está funcionando e há problemas de formatação. No servidor de homologação anterior há um exemplo da página funcionando melhor:

http://portal-mapas.conexaobrasil.org/2017/05/09/class-aptent-taciti-sociosqu-ad-litora-torquent-per-conubia-nostra-per-inceptos-himenaeos/

**Comment by vgeorge** [comment]
## Formatação correta:

<img width="693" alt="captura de tela 2018-02-24 as 12 51 05" src="https://user-images.githubusercontent.com/329694/36630624-6c575618-1961-11e8-8ac1-7d02074e283c.png">


## Formatação atual:

<img width="727" alt="captura de tela 2018-02-24 as 12 50 59" src="https://user-images.githubusercontent.com/329694/36630625-783e8474-1961-11e8-88de-77c3dcc65c1e.png">

## Correções necessárias:

- [x] Remover sublinhado dos links
- [x] Cor do nome do usuário
- [x] Espaçamento entre parágrafos

## Problemas no Widget 

Ele está repetindo as categorias:

<img width="359" alt="captura de tela 2018-02-24 as 12 56 37" src="https://user-images.githubusercontent.com/329694/36630682-38584dc6-1962-11e8-97e2-f61f47502093.png">

**Comment by cabelotaina** [comment]
Nao esta repetindo apenas tinham o mesmo nome...

![image](https://user-images.githubusercontent.com/1827173/36630875-5e8fea00-194c-11e8-8a81-e045ab96fa25.png)

**Comment by vgeorge** [comment]
Corrigir no widget:

- [x] remover metadados que se referem a tutoriais (gestor, agente)
- [x] colocar newsletter

Ele deve ficar igual ao especificado aqui #14

**Comment by cabelotaina** [comment]
Esta ali a newsletter - http://hmg.mapasculturais.medialab.ufg.br/2018/02/22/dolore-enim-quis-est-proident/

**Comment by vgeorge** [comment]
Tem um problema de formatação no input da newsletter, é preciso remover o color do `.newsletter-form input` no css.

**Comment by thaisrigolon** [comment]
- [ ] Remover as categorias selecionadas abaixo, pois elas estão fixas.
![1](https://user-images.githubusercontent.com/18294515/37348051-f101fe56-26b1-11e8-9a08-56c5240efff9.png)

**Comment by cabelotaina** [comment]
Ola @thaisrigolon isso tem a ver com o funcionamento do wp, basicamente ele possui um conjunto de categorias que estão visiveis em:

![image](https://user-images.githubusercontent.com/1827173/37712372-6fa74fe0-2cf2-11e8-9fde-e1052638d2db.png)

Ao clicar no link acima vc vai cair em uma pagina como esta:

![image](https://user-images.githubusercontent.com/1827173/37712406-835aa9d8-2cf2-11e8-8d45-f5656db2058a.png)

Veja que aqui vc pode encontrar todas as categorias que foram criadas na fase de teste. Sendo assim vcs podem remover estas categorias.

Outro ponto importante é entender que cada post que tem essas categorias, e que foram gerados na fase de teste estão listados em posts.

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/edit.php

Vocês também podem remover eles uma vez que não são mais úteis.

![image](https://user-images.githubusercontent.com/1827173/37712475-c4bb5954-2cf2-11e8-8393-e3e883cf7c11.png)

**Comment by vgeorge** [comment]
O problema das categorias considero resolvido, falta exibir e colocar links paras as tags.

**Comment by thaisrigolon** [comment]
Todas as categorias estão aparecendo em todos os posts. E precisa aparecer somente as selecionadas. Como configuramos isso?

**Comment by cabelotaina** [comment]
Este eh o comportamento padrão do widget de categorias, ele mostra todas as categorias que existem no site. Dado que um usuario poderia clicar em qualquer categoria do site e ver quais sao os posts que existem para tal categoria, independente das categorias do post atual, isso permite que usuario tenha acesso a qualquer conteudo do tipo que ele esta vizualiando usando as categorias para navegar pelos mesmos. Quanto a conteudos de mesmo tipo o post que esta sendo vizualizado as tags ou mesmo as categorias poderiam ser usadas para tal.

Note que a diferença entre categorias e tags eh uma categoria tem hierarquia, existindo categorias maes e filhas. Em tags não existe essa possibilidade. Nesse sentido não sei o que foi combinado, é possivel colocar as categorias e as tags mas sempre vai ser necessario criar ambas, as tags sao menos poderosas, eu ficaria apenas com as categorias e nao usaria tags, a nao ser que alguem me convença do contrario, eu acredito que podemos fazer um novo widget que mostra apenas as categorias do post atual.... mas na pagina archive (pagina com a lista de posts) isso nao faria sentido algum. Dado que ali se encontram todos os posts. 

Note que outro problema eh que o sidebar (menu lateral direito) da pagina unica de post de da pagina da lista de posts sao iguais, sendo assim o widget teria que saber que esta em uma pagina de posts e se adequar ou fazemos uma sidebar diferente para cada um. Dado que não tenho ideia de se isso estava no levantamento de requisitos vou esperar um retorno do @vgeorge.

Se isso for parte do que foi combinado entre vocês vou ver como fazer para revisitar e desenvolver essa nova funcionalidade.

**Comment by vgeorge** [comment]
@cabelotaina O comportamento correto é exibir só as categorias do post no widget.

**Comment by cabelotaina** [comment]
para isso vamos ter que fazer uma reengenharia, aqui, pois nao foi especificado isso em nenhum lugar, vamos lá. Seria legal pensar isso nas próximas vezes. algum doc que descreve o comportamento, notadamente apenas o design não foi capaz disso.

**Comment by cabelotaina** [comment]
feito agora temos a sidebar e as categorias apenas devem mostrar o que for do post atual

**Comment by thaisrigolon** [comment]
Parece que o servidor caiu, não estou conseguindo homologar.

**Comment by cabelotaina** [comment]
Ola o servidor esta funcionando normal, gostaria que issue fosse validada.

**Comment by cabelotaina** [comment]
Essa issue tambem parece estar resolvida. Poderiam validar ela?

**Comment by Nathlis** [comment]
Homologada.
