### ISSUE TITLE
Wireframe - Suporte

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#6]

**Comment by miguelpeixe** [comment]
http://dev.aparabolica.com.br/mapasculturais/wireframe/html/support.html

**Cabeçalho da página** - Apresentação do suporte, busca de tutoriais e links de acesso rápido aos principais recursos do suporte (menos destaque mas importante para o usuário frequente)

**Apresentação de conteúdo externo/estático** - Manual e chat

**Tutoriais** - Lista de tutoriais, por ordem manual ou cronológica

**Categorias de tutorial** - Acesso rápido às categorias

**Formulário de newsletter**

**Comment by thaisrigolon** [comment]
Essa página será para os desenvolvedores e gestores?
Porque ficou um pouco confuso o que é para os gestores (que estão precisando de tutoriais e manuais de uso) e o que é para os desenvolvedores (que estão buscando documentação/informações técnicas/rocket chat)

É preciso ter um link para o Rocket Chat também. O ícone abaixo parece do Telegram. Nós temos um grupo da comunidade de desenvolvedores no Telegram também, mas o ideal seria ter mais um ícone para direcionar para o [Rocket Chat](http://chat.mapasculturais.org/home).

![1](https://cloud.githubusercontent.com/assets/18294515/24205480/44871faa-0efa-11e7-9e8a-66e65648b738.png)

**Comment by miguelpeixe** [comment]
Essa página propõe ter foco nos gestores. Houve um engano na escolha do ícone do chat. É possível que haja também um engano sobre o objetivo do chat. No mapa de arquitetura descrevemos o chat como item integrante da seção de suporte, talvez seja um equívoco, ele possivelmente pertence à área de comunidade (que mescla o debate técnico e conceitual).

![captura de tela de 2017-03-22 15-32-17](https://cloud.githubusercontent.com/assets/820752/24214702/1240d188-0f15-11e7-8a13-953b134fb777.png)

**Comment by thaisrigolon** [comment]
Entendi. É que o chat que temos é estritamente voltado para os técnicos mesmo. Não temos chat para os gestores...

**Comment by miguelpeixe** [comment]
Removemos dessa página e colocamos na página comunidade/delibera?

ref #18

**Comment by thaisrigolon** [comment]
Não, acho que podemos manter nessa página mesmo. Vamos propor uma nova nomenclatura ao enviar o texto da página que vai deixar claro o objetivo do chat. Não tem problema ficar nesta página.
