### ISSUE TITLE
Widget da seção tutoriais

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#60]
- [x] Título customizável
 - [x] Link para público alvo
 - [x] Lista de categorias de tutoriais

**Comment by vgeorge** [comment]
Não está funcionando corretamente:

http://hmg.mapasculturais.medialab.ufg.br/tutorials/

**Comment by cabelotaina** [comment]
Agora esta ok http://hmg.mapasculturais.medialab.ufg.br/tutoriais/

**Comment by vgeorge** [comment]
Porque está aparecendo este input no widget?

<img width="335" alt="captura de tela 2018-03-01 as 13 52 19" src="https://user-images.githubusercontent.com/329694/36847983-cfd0e692-1d57-11e8-8c43-8873b9d263db.png">

**Comment by vgeorge** [comment]
A linha que está gerando o input é essa https://github.com/institutotim/wp-theme-mapasculturais/blob/to-validate/inc/tutorials/widget.php#L73.

Questões ainda pendentes:

- [x] remover input
- [x] remover lista de categorias gerais, apenas as de tutoriais devem aparecer

**Comment by vgeorge** [comment]
Issue pronta para validação, depende de que integração com homologação volte a funcionar.

**Comment by vgeorge** [comment]
A issue não está resolvida. O input voltou, devido a reversão do commit e37e8e6589bb290c07ea33c99988516e416be865, que fez com que o site parasse de funcionar sem exibir nada no log. Imagino que no local não aparece o erro porque não foi configurado um widget. Tem que ver a api desse componente WP_Widget para entender qual o problema. cc @cabelotaina

**Comment by cabelotaina** [comment]
@vgeorge  Por favor check se o widget esta ok.

**Comment by Nathlis** [comment]
Homologada
