### ISSUE TITLE
Página de tutoriais

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#61]
- [x] Cabeçalho
    - [x] Seleção dropdown de público alvo
    - [x] Ferramenta de busca (resultado aparece no mesmo layout)
 - [x] Lista de tutoriais
   - [x] Categoria, complexidade, público alvo e versões relacionadas
   - [x] Paginação
 - [x] Integração de sidebar específica na barra lateral

**Comment by cabelotaina** [comment]
Pessoal a pagina que lista os tutoriais ela não tem nenhuma menção a versões relacionadas:

![image](https://user-images.githubusercontent.com/1827173/35351015-cfa5f916-0126-11e8-87e6-c20c2bee35f5.png)

Posso colocar logo abaixo de todas?

**Comment by miguelpeixe** [comment]
A informação de versão poderia estar só na página do tutorial mesmo

**Comment by vgeorge** [comment]
O estilo da página está quebrado.

**Comment by cabelotaina** [comment]
Mesmo problema, preciso de mais informações para saber o que esta ocorrendo pois não tenho como reproduzir o bug.

**Comment by vgeorge** [comment]
Falta tradução e o estilo está quebrado:

http://hmg.mapasculturais.medialab.ufg.br/tutorials/mauris-mattis-elit-ac-justo-commodo-pulvinar-quisque-porta-libero-massa-in-interdum-facilisis/

**Comment by cabelotaina** [comment]
O estilo aparentemente esta ok, quanto a tradução foi feita, mas estamos com um problema de caracter encode no form de adicionar tutoriais:

![image](https://user-images.githubusercontent.com/1827173/36625187-b483d898-18f9-11e8-92ff-be11426290ea.png)

**Comment by vgeorge** [comment]
Subi as seguintes alterações:
- correção do encoding no form
- mudança do slug de "tutorials" para "tutoriais"
- tradução e geração correta dos labels de público-alvo, dificuldade e versão.

http://hmg.mapasculturais.medialab.ufg.br/tutoriais/mauris-mattis-elit-ac-justo-commodo-pulvinar-quisque-porta-libero-massa-in-interdum-facilisis/

Persistem os seguintes problemas:

- [x] não são geradas todas as versões associadas, no exemplo acima só aparece uma delas
- [x] a formatação das versões está incorreta
- [ ] o widget não é gerado ([exemplo](http://portal-mapas.conexaobrasil.org/tutorials/como-fazer-uma-instalacao-local-da-plataforma/))

**Comment by vgeorge** [comment]
A homologação conta com quatro tutoriais, mas apenas um está aparecendo na lista:

http://hmg.mapasculturais.medialab.ufg.br/tutoriais/

**Comment by vgeorge** [comment]
Ainda há 2 problemas de front-end:

- [ ] o seletor no cabeçalho está sem formatação
- [ ] o box onde aparece a complexidade quebra a linha para as complexidades "média" e "avançada"

**Comment by cabelotaina** [comment]
A pagina eh esta

http://hmg.mapasculturais.medialab.ufg.br/tutoriais/

O seletor sem formatação é este:

![image](https://user-images.githubusercontent.com/1827173/37690799-35474442-2c8c-11e8-9c71-c97fb47138a3.png)

Qual seria o design que mostra como deve ser o seletor?

Quanto a quebra de linha me parece algo natural, por se tratar de duas palavras distintas dentro de um paragrafo, penso que ele deve quebrar mesmo, e isso depende da resolução do monitor, mais uma vez me parece algo relacionado a responsividade do framework que estamos usando, não sei fazer isso ficar sempre na mesma linha.

![image](https://user-images.githubusercontent.com/1827173/37690932-08873786-2c8d-11e8-80e9-0e4cc98f7da9.png)

![image](https://user-images.githubusercontent.com/1827173/37690935-120411d0-2c8d-11e8-9e87-8b9952e6b297.png)
 
Eu tive que mecher no tamanho da tela para ver a quebra.

**Comment by vgeorge** [comment]
Está ok, agora só falta resolver o estilo do seletor. @miguelpeixe

**Comment by Nathlis** [comment]
Homologada.
