### ISSUE TITLE
Página única de tutorial

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#62]
- [x] Cabeçalho
   - [x] Link para home de tutoriais
   - [x] Categoria(s) do tutorial
   - [x] Título
 -  [x] Metadados (público alvo, complexidade, versões relacionadas)
 -  [x] Integração de sidebar específica (mesma da página da tutoriais) na barra lateral
 -  [x] Corpo do tutorial

**Comment by vgeorge** [comment]
Estilo está quebrado, consulte o #14.

<img width="1002" alt="captura de tela 2018-01-27 as 12 21 17" src="https://user-images.githubusercontent.com/329694/35471919-fbe151dc-035c-11e8-805c-86c0ffbc4ae2.png">

**Comment by cabelotaina** [comment]
Como havia colocado na reunião sugiro que vocês façam esse tipo de personalização do css, por conta de não ter muita intimidade com isso. Só para que eu entenda melhor, o problema esta no dropdown menu certo @vgeorge, neste caso o  @miguelpeixe poderia dar um help nessa parte?

**Comment by vgeorge** [comment]
A formatação melhorou, mas há um erro no console quando o conteúdo tem mais de 1 parágrafo.

**Comment by vgeorge** [comment]
Na verdade é o problema no console não é relacionado à pagina, mas ao erro #65

**Comment by vgeorge** [comment]
Consertei erros relacionados à integração com o backend, label de categoria e lista de versões na barra, mas o link para as taxonomias não estão funcionando.

**Comment by vgeorge** [comment]
Parece ok agora.

**Comment by Nathlis** [comment]
Homologada.
