### ISSUE TITLE
Campo de busca do cabeçalho

### ISSUE THREAD

**Issue by miguelpeixe** [institutotim/wp-theme-mapasculturais#63]

**Comment by cabelotaina** [comment]
done

**Comment by vgeorge** [comment]
Ao fazer uma busca é retornado um 404:

<img width="1027" alt="captura de tela 2018-01-27 as 11 52 14" src="https://user-images.githubusercontent.com/329694/35471700-91ca8f4c-0358-11e8-9dfe-293f3b3459b4.png">

**Comment by cabelotaina** [comment]
Necessita habiltar o tema e salvar os permalinks para rewrite tags adicionar as novas rotas.

**Comment by thaisrigolon** [comment]
Quando pesquisamos uma palavra que não existe no portal, o texto que aparece é em inglês.

Em qual local podemos alterar esse texto?

![1](https://user-images.githubusercontent.com/18294515/36802789-9de4976e-1c94-11e8-98f8-d60316a0f117.png)

**Comment by cabelotaina** [comment]
Em languages/pt_BR.po, já realizei a alteração.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
