### ISSUE TITLE
Itens da linha do tempo não aparecem

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#66]
Criei alguns posts para a linha do tempo, mas eles não aparecem:

http://hmg.mapasculturais.medialab.ufg.br/linha-do-tempo/

**Comment by cabelotaina** [comment]
Isso acontece porque timeline não é um template, para acessar a timeline é necessário acessar o link:

http://hmg.mapasculturais.medialab.ufg.br/timeline/

Removi o cabeçalho que permite adicionar ela como um template para evitar esse tipo de confusão.

**Comment by vgeorge** [comment]
Legal. Removi a página que havia criado e alterei o slug para "linha-do-tempo":

http://hmg.mapasculturais.medialab.ufg.br/linha-do-tempo

**Comment by thaisrigolon** [comment]
- [x] Ao atualizar um item da linha do tempo e clicar em **publicar/atualizar** a seguinte mensagem aparece duas vezes. Ela é realmente necessária?
![1](https://user-images.githubusercontent.com/18294515/36808275-629e6efa-1ca3-11e8-816b-b97ec0c30573.png)

- [x] O link do menu para direcionar até a página da linha do tempo não está funcionando:
![2](https://user-images.githubusercontent.com/18294515/36808866-1ff8c3a0-1ca5-11e8-8698-80eef20c1d3c.png)

**Comment by cabelotaina** [comment]
@thaisrigolon  - "O link do menu para direcionar até a página da linha do tempo não está funcionando" Parece que já foi resolvido.

Eu tb notei isso, mas foge a minha alçada, acredito que isso deve ter a ver com a configuração do pessoal do UFG. @vgeorge pode checar isso?

**Comment by vgeorge** [comment]
O link do menu está resolvido, agora falta remover esse warning.

Olhando o blame do arquivo acho que só pode ser a mudança do slug:

https://github.com/institutotim/wp-theme-mapasculturais/blame/to-validate/inc/timeline-items.php

**Comment by cabelotaina** [comment]
Ola eu tenho mention nessa issue, eu tenho que fazer algo aqui, não entendi qual seria o problema, entrei na time line e parece tudo estar funcionando normal... http://hmg.mapasculturais.medialab.ufg.br/linha-do-tempo/

**Comment by vgeorge** [comment]
@Nathlis Aqui parece que está tudo ok.

**Comment by Nathlis** [comment]
@vgeorge  não funciona quando você clica em "Histórico" no rodapé. Como eu coloquei essa questão na issue #84 pode fechar essa.

Linha do tempo funcionando. Homologada.
