### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#69]
- [x] O menu superior do protótipo aprovado não está batendo com o menu do ambiente de homologação. Os links são diferentes:
- Protótipo aprovado
![1](https://user-images.githubusercontent.com/18294515/36850344-43f64bba-1d45-11e8-8ce7-ffc7dc4b31c6.png)
- Ambiente de homologação
![2](https://user-images.githubusercontent.com/18294515/36850354-4921dd8e-1d45-11e8-80f9-00f9c37ba9f7.png)

- [x] Nos links dos posts do blog da rede, precisamos alinhar como foi aprovado no protótipo. Deixar o título em negrito e com o nome da instalação abaixo da foto.
![1](https://user-images.githubusercontent.com/18294515/36850473-afef94a2-1d45-11e8-9553-087bc78e1546.png)
![2](https://user-images.githubusercontent.com/18294515/36850484-b69c8c38-1d45-11e8-9108-d49ed1911bc8.png)

- [x] O rodapé do protótipo aprovado não está batendo com o rodapé do ambiente de homologação. Os links são diferentes:
- Protótipo aprovado
![1](https://user-images.githubusercontent.com/18294515/36850602-074415a2-1d46-11e8-807b-c1183e48faf1.png)
- Ambiente de homologação
![2](https://user-images.githubusercontent.com/18294515/36850595-04eef614-1d46-11e8-9044-7b0d06ebcfb9.png)

- [x] Os links do github e discussão devem direcionar para uma nova aba ao serem clicados.
![1](https://user-images.githubusercontent.com/18294515/36850704-3d224ad6-1d46-11e8-9be2-c45abcc2bfd1.png)
![1](https://user-images.githubusercontent.com/18294515/36850716-46125bf4-1d46-11e8-9c76-43262b8ceb0e.png)

- [x] Diminuir a marca do IT no rodapé e tirar o ponto após a marca
![1](https://user-images.githubusercontent.com/18294515/36850876-9b069ff8-1d46-11e8-9c04-3127b11d6d3e.png)

- [x] Aumentar um pouco nome "PORTAL MAPAS CULTURAIS"
![1](https://user-images.githubusercontent.com/18294515/36850948-c77f773a-1d46-11e8-8885-33057c50d0cf.png)

**Comment by vgeorge** [comment]
Thaís, fizemos modificações e abrimos issues específicas para os problemas:

- Thumbnails não são exibidos: https://github.com/institutotim/wp-theme-mapasculturais/issues/82
- Título da página inicial: https://github.com/institutotim/wp-theme-mapasculturais/issues/83

Se não estiver faltando nada, sugiro o encerramento.
