### ISSUE TITLE
Wireframe - Página Estática

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#7]

**Comment by miguelpeixe** [comment]
http://dev.aparabolica.com.br/mapasculturais/wireframe/html/

**Cabeçalho** - Logo, menu e busca

**Hero (eyecandy)** - Slogan/descrição curta, convite ao acesso às principais áreas, resumo dos dados das instalações (destacando impacto/alcance do software)

**Seção conteúdo dinâmico** - Mais informações sobre o MC, últimos posts e formulário para newsletter

**Convite à comunidade** - Seção constante em todas as páginas, convida usuário à participar da comunidade, apresenta critérios/métodos de participação e importância do debate democrático na contribuição do software

**Rodapé** - Links institucionais (eventual licença de uso, acesso à termos de uso, etc)

**Comment by thaisrigolon** [comment]
**Páginas estáticas:**

# O que é
Página simples com um texto sobre a iniciativa.

# Histórico
Página simples com um texto sobre o histórico do projeto e um link para a página da linha do tempo.

# Parceiros
Página simples com descrição breve e marcas de todos os parceiros com link clicável.

# Mapas como serviço 
Página simples com opção de widgets ao lado do texto.

# Notícias
Ter uma página estática simples para as notícias oficiais (blog do Instituto TIM).

# Contato
- Página simples com uma descrição breve e um formulário para contato.
- Retirar a parte "Faça parte da comunidade"

**Comment by miguelpeixe** [comment]
Ok, suponho que não há necessidade de ter wireframes para cada uma dessas páginas, considerando que haverá templates de página disponíveis para que seja selecionado o template de página adequado para o conteúdo.

Sobre a página Notícias, faço referência ao #8
 
Para melhor visualizar esse conceito incluí o wireframe para template de página de largura cheia. Tendo assim as 2 opções: páginas com barra lateral e páginas de largura cheia.

http://dev.aparabolica.com.br/mapasculturais/wireframe/html/page.html
http://dev.aparabolica.com.br/mapasculturais/wireframe/html/page-full-width.html

Vale lembrar que nesses wireframes (`page.html` e `page-full-width.html`)  estamos nos referindo às páginas como tipo de contéudo, não todas as páginas do site. Por exemplo, a página de notícias é uma página dinâmica, criada e atualizada automaticamente sem necessidade de criação, edição ou qualquer tipo de gestão da própria.

c668484cb093084fbbc126d80792b0f913519217

**Comment by thaisrigolon** [comment]
Ok, não precisamos ter wireframes para cada uma dessas páginas estáticas, já que teremos os templates para cada uma delas.
