### ISSUE TITLE
Mapa da Rede

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#70]
- [x] É possível adicionar um contorno branco, por exemplo, nos pins do mapa? No ambiente de homologação tínhamos a visão de apenas 1 pin e agora, com pins próximos acaba gerando uma visualização confusa. Talvez o contorno facilitaria a exibição.
![1](https://user-images.githubusercontent.com/18294515/36851306-b485a2de-1d47-11e8-9211-42da1c1a9571.png)

- [ ] Na coluna "conheça as iniciativas" é possível ter um botão para expandir? Da forma que está podemos ter uma lista enorme de instalações e poucos posts. Se houver a possibilidade de colocar um botão expandir também pode ser colocado ao lado, no blog da rede.
![1](https://user-images.githubusercontent.com/18294515/36851443-f898390a-1d47-11e8-901e-4de7fbfbd271.png)
![1](https://user-images.githubusercontent.com/18294515/36851466-06ab9050-1d48-11e8-850e-13841ba21638.png)

- [x] Quando não há números numa entidade do mapa, no caso projetos (exemplo abaixo) está aparecendo **null** no gráfico:
![1](https://user-images.githubusercontent.com/18294515/36851590-4da4b504-1d48-11e8-860d-a2eaeeee5ff6.png)

- [x] Nos links dos posts do blog da rede e das iniciativas, precisamos alinhar como foi aprovado no protótipo. Deixar o título em negrito e com o nome da instalação abaixo da foto.
- Protótipo aprovado
![1](https://user-images.githubusercontent.com/18294515/36851681-91278e00-1d48-11e8-80a2-b62f50146dda.png)
- Ambiente de homologação
![2](https://user-images.githubusercontent.com/18294515/36851689-982da9c8-1d48-11e8-82bd-8702ce8f5dd3.png)

- [ ] Será que conseguimos colocar alguns limites nesse mapa, para o usuário pelo menos ter uma ideia de em que estado ele está clicando? Quando damos o zoom isso acontece, mas na primeira visão está tudo em branco.
![1](https://user-images.githubusercontent.com/18294515/36851765-cbb79ab0-1d48-11e8-96c2-6b78caace973.png)

- [x] Tirar ponto final da frase:
![1](https://user-images.githubusercontent.com/18294515/36851837-04bba2c0-1d49-11e8-8981-2094be5132e6.png)

**Comment by vgeorge** [comment]
Foram feitas as alterações nos items ticados. Comentários:

- Sobre a "Conheça as iniciativas", será necessário desenhar e desenvolver paginação para esta coluna, pois ela não tem página própria. Foi criada uma issue específica: https://github.com/institutotim/wp-theme-mapasculturais/issues/73

- Foi alterado do estilo da coluna "blog da rede", mas há um problema nos thumbnails. Issue sobre isso: https://github.com/institutotim/wp-theme-mapasculturais/issues/74

- Sobre o mapa, não dá para incluir os limites estaduais no zoom, mas estamos discutindo uma possível solução aqui: https://github.com/institutotim/wp-theme-mapasculturais/issues/76

@thaisrigolon, se não estiver faltando algo que não listei, sugiro encerrar esta issue e acompanhar pelas que foram criadas.
