### ISSUE TITLE
Parceiros

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#71]
- [x] Deixar o link do Instituto TIM em branco, como estava no protótipo aprovado:
![1](https://user-images.githubusercontent.com/18294515/36852117-bc9ca380-1d49-11e8-9402-0496ce428507.png)
No ambiente de homologação está em azul:
![1](https://user-images.githubusercontent.com/18294515/36852232-f28afc08-1d49-11e8-944c-35d489597087.png)

- [x] Os links que estão em cada logo precisam abrir numa nova aba

**Comment by HeloMubarack** [comment]
Ainda em "parceiros", em logos:

_Ao clicar no logo da Prefeitura de Sobral, somos direcionados para esse link com erro:

![image](https://user-images.githubusercontent.com/27974406/36859626-bb4215ec-1d5d-11e8-98b9-03215eb1b9c3.png)

Link correto para usarmos: (http://secjel.sobral.ce.gov.br/)

_O logo do Governo da Paraíba está cortado na parte de cima: 

![image](https://user-images.githubusercontent.com/27974406/36859650-d14d64a4-1d5d-11e8-92fa-24a4d11cb44f.png)

Por gentileza, substituir por esse:

![image](https://user-images.githubusercontent.com/27974406/36859746-15ee2152-1d5e-11e8-81f3-198ee2fc321d.png)

_Gostaríamos também que, ao clicar nos links dos logos, fosse aberta outra janela. Da maneira atual, você sai do Portal Mapas e na mesma aba é aberto o site do link.

**Comment by vgeorge** [comment]
Thaís, foram feitas as alterações. A última linha ficou apertada e pensei em dividi-la em duas. Está de acordo? Quais logos ficariam na última linha?

**Comment by thaisrigolon** [comment]
Sim, pode dividir a última linha em duas. Deixando na penúltima 5 logos e na última 4 logos.
Pode seguir a mesma ordem que está agora...

**Comment by thaisrigolon** [comment]
- [x] Conforme comentário anterior, pode dividir a última linha em duas. Deixando na penúltima 5 logos e na última 4 logos.

- [x] Diminuir a margem de altura inferior e deixar o espaçamento superior e inferior no mesmo tamanho:
![1](https://user-images.githubusercontent.com/18294515/37527194-37268568-2910-11e8-8482-aafa33f44bda.png)

**Comment by cabelotaina** [comment]
corrigido

**Comment by thaisrigolon** [comment]
@cabelotaina as alterações ainda não estão aparecendo no ambiente de homologação... limpei o cache...

**Comment by vgeorge** [comment]
Subi o código agora:

http://hmg.mapasculturais.medialab.ufg.br/parceiros/

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
