### ISSUE TITLE
Erro ao tentar navegar no Wordpress

### ISSUE THREAD

**Issue by HeloMubarack** [institutotim/wp-theme-mapasculturais#72]
A página exibe esse erro tanto para mim quanto para Thaís, sendo que já estávamos logadas normalmente antes.

![image](https://user-images.githubusercontent.com/27974406/37053056-e57b6674-2159-11e8-84cd-b79d1ecb3857.png)

**Comment by vgeorge** [comment]
Oi Heloísa, fiz um teste aqui e parece ok. Resetei sua senha para ter acesso com seu usuário e funcionou também. Pode tentar novamente, por favor?

**Comment by HeloMubarack** [comment]
Oi, Vitor. Agora está funcionando normalmente para nós duas. Obrigada.
