### ISSUE TITLE
Paginação de instâncias no mapa da rede

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#73]
Quando há mais de uma dezena de instâncias cadastradas na plataforma a página do mapa fica muito longa e há assimetria com a coluna blog da rede. Não é necessária paginação da coluna do blog da rede, pois ele tem uma página própria, mas é necessária paginação das instâncias. 

Como ainda não havíamos considerado esta funcionalidade, será preciso desenhar os botões que farão a paginação.

**Comment by vgeorge** [comment]
Como avançamos nesta issue, @miguelpeixe?

**Comment by cabelotaina** [comment]
Galera ontem eu tentei iniciar alguma solução em cima disso, mas tive problemas com rebase e acho que vou pegar o projeto que esta online e reiniciar o que estou fazendo a partir dele. Pois esta dando varias quebras.

**Comment by vgeorge** [comment]
Essa depende de uma solução de front-end primeiro.

**Comment by miguelpeixe** [comment]
A lista de instâncias exibe as primeiras 4, com um botão de expandir para exibir as restantes.

**Comment by Nathlis** [comment]
Não foi prevista uma página interna para as **Iniciativas**? No momento não tem muitas, mas e quando tiver?

**Comment by miguelpeixe** [comment]
Não foi previsto.

**Comment by Nathlis** [comment]
Tudo bem. Aprovado.
