### ISSUE TITLE
Thumbnails da página da rede

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#74]
Questões:

- [x] Coluna "blog da rede" só mostra 1 thumbnail e distorcido
- [x] Coluna "conheça as iniciativas" tem imagem distorcida se o usuário não tem um thumb

Link para a página de validação:

http://hmg.mapasculturais.medialab.ufg.br/rede

**Comment by vgeorge** [comment]
O problema persiste. @cabelotaina @miguelpeixe

**Comment by cabelotaina** [comment]
Pelo que entendi era apenas 1 thumb na coluna blog da rede. Esta issue esta fechada mesmo @vgeorge posso desconsiderar ou não?

**Comment by vgeorge** [comment]
É preciso corrigir os thumbs, @miguelpeixe e @cabelotaina

**Comment by cabelotaina** [comment]
Pessoal tentei aqui de varias formas melhorar o thumbs das instancias e realmente eu não tenho o dom pra isso hahaha, nem consegui fazer o negocio chegar perto de mudar.

**Comment by Nathlis** [comment]
Homologada.
