### ISSUE TITLE
Pautas

### ISSUE THREAD

**Issue by HeloMubarack** [institutotim/wp-theme-mapasculturais#75]
As "Pautas" estão relacionadas ao plugin Delibera?

![image](https://user-images.githubusercontent.com/27974406/37092776-d7b1f228-21eb-11e8-9357-0a139268e994.png)

![image](https://user-images.githubusercontent.com/27974406/37092759-c6845a9a-21eb-11e8-8705-bf4615036b9d.png)

**Comment by cabelotaina** [comment]
sim

**Comment by cabelotaina** [comment]
@vgeorge acredito que essa issue pode ser fechada
