### ISSUE TITLE
Limites estaduais no mapa

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#76]
Nesta [issue](https://github.com/institutotim/wp-theme-mapasculturais/issues/70) foi comentado que o mapa fica muito "vazio" com o zoom inicial, mas não temos como incluir os limites estaduais no mapa sem fazer alterações consideráveis na plataforma. Uma possível solução seria o mapa dar zoom nos limites dos pontos (fit to bounds), o deve fazer com que caia quase sempre no zoom menor. 

O que acha desta solução, @miguelpeixe?

**Comment by cabelotaina** [comment]
@miguelpeixe veja o que o @vgeorge comentou, de acordo com sua resposta faço a modificação.

**Comment by cabelotaina** [comment]
ping @miguelpeixe @vgeorge

**Comment by Nathlis** [comment]
Homologada.
