### ISSUE TITLE
Dúvida sobre imagem da home de notícias

### ISSUE THREAD

**Issue by HeloMubarack** [institutotim/wp-theme-mapasculturais#77]
Quais são as dimensões da imagem de destaque da home de notícias? 

![image](https://user-images.githubusercontent.com/27974406/37092938-5dcc583a-21ec-11e8-9422-dacbe1da5a78.png)

**Comment by cabelotaina** [comment]
836x327px @vgeorge se for apenas isso favor fechar a issue ou colocar para to-validate.
