### ISSUE TITLE
Como alteramos o texto da parte rosa de uma página?

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#79]
Conseguimos inserir o conteúdo da página normalmente, mas na parte rosa como fazemos?

Link: http://hmg.mapasculturais.medialab.ufg.br/o-que-e/

![1](https://user-images.githubusercontent.com/18294515/37093725-22e407c4-21ef-11e8-9634-a1d1d493f5ea.png)

**Comment by cabelotaina** [comment]
Pelo que vi ele é um texto gerado automaticamente, a principio não seria possivel alterar, mas não foi implementada ainda, obrigado por sinalizar que ele não foi implementado acabei de colocar isso para funcionar da maneira esperada como um excerto.

@vgeorge se essa for a funcionalidade correta por favor feche a issue ou coloque para validação.

**Comment by vgeorge** [comment]
Parece que há um problema na integração do código via Travis CI e as mudanças não estão se refletindo na homologação, vamos aguardar o @walisonjose avaliar.

**Comment by vgeorge** [comment]
O servidor voltou. Agora a página mostra um excerto automático e não há como editá-lo no painel administrativo.

**Comment by thaisrigolon** [comment]
Conseguimos avançar na resolução dessa issue?

**Comment by cabelotaina** [comment]
@thais vc gostaria de pode colocar esse conteudo por separado ou pode ser como esta atualmente. Atualmente ele é um pedaço do conteudo publicado.

**Comment by thaisrigolon** [comment]
@cabelotaina, gostaríamos de colocar em separado.

**Comment by thaisrigolon** [comment]
- [ ] É possível diminuir a margem de altura da parte rosa? 
![screenshot_1](https://user-images.githubusercontent.com/18294515/37527783-9bb99c62-2911-11e8-93b2-5343e6ee4c8a.png)


- [ ] Diminuir o tamanho da letra para o mesmo padrão do texto também:
![1](https://user-images.githubusercontent.com/18294515/37527809-adfd4626-2911-11e8-9c9a-47d4cfab00d8.png)

**Comment by vgeorge** [comment]
@thaisrigolon Alterei o estilo e agora vc pode editar o texto no resumo (excerto) da página.

**Comment by thaisrigolon** [comment]
Em qual local do painel conseguimos editar o texto do excerto?
![1](https://user-images.githubusercontent.com/18294515/37724013-9de4521a-2d0e-11e8-875b-909fd929571c.png)

**Comment by vgeorge** [comment]
O excerto fica no box cujo título é "Resumo" e está logo abaixo do box "Revisões".

**Comment by Nathlis** [comment]
Não consegui encontrar onde faço a alteração do texto. Pode me ajudar @vgeorge ? Só encontro o resumo abaixo mas não é editável:

![Revisões ‹ Portal do Mapas Culturais — WordPress.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/596cb7a89e3565001f4cdc90/125516c66e82c728ace21e0d46da918c2a91207c8afaffc14484b0a4265433722544a72430a8e238be513b221a030ae903090607ec2b398fb6d16332de3c49b8922e4d68d47d53f3e2d74cfb13b0328e47d6bfbfdb4fc7bc3f25ef8d8c4f3e1d0d118aac5833a78b57da1aa715b51208fd596321f47c247d4f9e1f702e6e652eaffadc568e8468b6f7.png)

**Comment by vgeorge** [comment]
Natalia, fiz um teste aqui e está funcionando. Por exemplo, para editar a página "O que é?", acesse o link:

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/post.php?post=268&action=edit

Role até aparecer um box cujo título é "Resumo", edite o texto e publique. Se não estiver conseguindo para alguma página, por favor, informe o link.

**Comment by Nathlis** [comment]
Não consigo alterar o box rosa abaixo:

http://hmg.mapasculturais.medialab.ufg.br/o-que-e/

![1](https://user-images.githubusercontent.com/18741130/39627822-73212f1c-4f7d-11e8-8191-73188cf1661e.png)

**Comment by vgeorge** [comment]
Oi Natália, você está acessando com um usuário admin, correto? Verifique se o resumo está habilitado acessando as opções de tela:

![captura de tela 2018-05-04 as 09 47 11](https://user-images.githubusercontent.com/329694/39628695-3ff50a16-4f80-11e8-9c5b-2c63bf3c4d54.png)

Depois verifique se opção de resumo está marcada como ativa:

![captura de tela 2018-05-04 as 09 48 22](https://user-images.githubusercontent.com/329694/39628731-5b730e64-4f80-11e8-9729-13ba26f0a69f.png)

Se as condições acima estiverem de acordo, vc deve ver a caixa de resumo. Se ainda não aparecer, tente acessar em outro navegador ou desabilitar adblocker.

**Comment by Nathlis** [comment]
Consegui!! 

- [ ] Caso eu não queira o resumo e deixar desabilitado, o sistema pega um pedaço do conteudo publicado? Porque deixei desabilitado e apareceu isso:

![portal do mapas culturais](https://user-images.githubusercontent.com/18741130/39630845-f791c596-4f86-11e8-852f-4a13571ec4a3.png)

- [ ] Só por dúvida, é possível esse quadro não existir?

**Comment by Nathlis** [comment]
Aprovado.
