### ISSUE TITLE
Wireframe - Blog

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#8]
Propor a partir do plugin delibera

**Comment by thaisrigolon** [comment]
http://dev.aparabolica.com.br/mapasculturais/wireframe/html/blog.html

- [ ] Essa página seria do Blog da Rede. É possível termos outra página simples somente com matérias institucionais que seria nomeada de **Notícias**? Assim as informações não ficariam juntas no blog da Rede. Pode ser?

- [ ] Precisa ter paginação e não deixar com rolagem longa...
![1](https://cloud.githubusercontent.com/assets/18294515/24206017/cec75d3c-0efb-11e7-91a3-6566121895f9.png)

**Comment by miguelpeixe** [comment]
A ideia desse wireframe é contemplar a diagramação de ambas as páginas (notícias e blog da rede), pois a arquitetura é a mesma, alteram os títulos, algumas informações na barra lateral (que serão dinâmicas através de widgets) e claro, o conteúdo dinâmico dos posts que estarão alí.

O widget customizado que será desenvolvido para exibição na página do blog da rede é a listagem de usuários mantenedores. Esse widget poderá ser inserido em ambas as barras laterais, à critério do editor do site.

Alterei o título do blog, o botão primário está agora ativo para o Blog da rede para evidenciar que essa é a página ativa e incluí a paginação.

http://dev.aparabolica.com.br/mapasculturais/wireframe/html/blog.html

c74d39560475ecb88efabcf0fb405d9d74b28f72

**Comment by thaisrigolon** [comment]
Então não há como ter essa página específica para as notícias? Seria legal se desse pra fazer essa distinção...

**Comment by miguelpeixe** [comment]
A página existirá sim, só não vejo necessidade de ter 2 wireframes iguais, mas posso fazê-lo sem problemas.

**Comment by thaisrigolon** [comment]
Era só pra confirmar se vai ter. Não precisa de wireframe.
