### ISSUE TITLE
Tags das notícias

### ISSUE THREAD

**Issue by HeloMubarack** [institutotim/wp-theme-mapasculturais#80]
As tags adicionadas a uma notícia (Ex. "Oficina para discutir próximos passos de Mapas Culturais") não estão aparecendo. Como podemos torná-las visíveis na publicação?

**Comment by cabelotaina** [comment]
No processo de desenvolvimento do tema as tags não foram mencionadas por isso elas não apresentadas. Atualmente apenas as categorias que nos apresentamos.

**Comment by cabelotaina** [comment]
@vgeorge veja se podemos fechar essa issue.

**Comment by vgeorge** [comment]
@cabelotaina Dá uma olhada na issue https://github.com/institutotim/wp-theme-mapasculturais/issues/14, ela tem o que foi aprovado para a página de notícias. As tags devem aparecer no cabeçalho. Como não dá para se colocar muitas tags, sugiro exibir no máximo 5.

**Comment by cabelotaina** [comment]
Pelo que entendi da issue #81 era apenas retirar as categorias do topo da pagina, é isso, se for já retirei, se não eu coloco elas de volta com o limite de apenas 5 categorias.

**Comment by vgeorge** [comment]
@cabelotaina A Heloísa se referiu a tags, não a categorias. Como comentei anteriormente, as tags estão previstas, de acordo com o que já estava no código e específicado na issue #14. Ao invés de criar link para tag, está sendo criado link para categorias:

http://hmg.mapasculturais.medialab.ufg.br/2018/03/13/gestores-e-desenvolvedores-de-mapas-se-reunem/

**Comment by vgeorge** [comment]
Aqui está o problema, essa lista está referenciando categorias, e não tags:

<img width="803" alt="captura de tela 2018-03-21 as 15 34 40" src="https://user-images.githubusercontent.com/329694/37719701-810eb040-2d1d-11e8-812f-321411158d4c.png">

**Comment by HeloMubarack** [comment]
Oi, pessoal. Conseguimos adicionar o widget das TAGs e agora elas estão sendo exibidas normalmente ao lado dos posts.
