### ISSUE TITLE
Categorias - como posicioná-las

### ISSUE THREAD

**Issue by HeloMubarack** [institutotim/wp-theme-mapasculturais#81]
Como nós escolhemos as categorias que aparecem de destaque no header de notícias e na lateral das páginas internas de notícias? Ou ele puxa todas as que a gente tiver, automaticamente?

**Comment by cabelotaina** [comment]
Ele puxa todas as categorias que vc tiver automaticamente.

**Comment by cabelotaina** [comment]
Se for apenas isso sugiro fechar a issue @vgeorge

**Comment by vgeorge** [comment]
@HeloMubarack e @thaisrigolon,

A versão inicial da lista de notícias não contava com categorias no topo https://github.com/institutotim/wp-theme-mapasculturais/issues/14. Não lembro exatamente por que as colocamos depois, mas sugiro a retirada, pois elas estão acessíveis no widget lateral. Não há maneira de marcar categorias como destacadas ou ordená-las sem ser por ordem alfabética, e assim fica difícil colocá-las de maneira adequada no topo.

**Comment by thaisrigolon** [comment]
Ok, pode retirar e mantemos apenas no widget lateral.

**Comment by vgeorge** [comment]
Ok, para que esta issue esteja resolvida é preciso remover os botões de categorias no cabeçalho desta página:

http://hmg.mapasculturais.medialab.ufg.br/noticias/

**Comment by vgeorge** [comment]
@cabelotaina as categorias continuam aparecendo no topo:

http://hmg.mapasculturais.medialab.ufg.br/noticias/

**Comment by cabelotaina** [comment]
Veja se ao dar um refresh geral elas aparecem, aqui elas nao aparecem mais.

**Comment by Nathlis** [comment]
Homologada.
