### ISSUE TITLE
Thumbnails da página inicial

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#82]
Só estão aparecendo para o primeiro post do blog da rede.

**Comment by cabelotaina** [comment]
Eu segui o que esta no padrão http://portal-mapas.conexaobrasil.org/

**Comment by vgeorge** [comment]
Os thumbnails só estão aparecendo no primeiro item da lista:

<img width="557" alt="captura de tela 2018-03-09 as 11 53 20" src="https://user-images.githubusercontent.com/329694/37206423-7e37fc96-2390-11e8-9e5f-543e7f1090e0.png">

**Comment by cabelotaina** [comment]
O thumb é proveniente da imagem destacada, é necessário dispor de imagem destacada no post para que o thumb apareça. Veja este post com imagem destacada.

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/post.php?post=375&action=edit

![image](https://user-images.githubusercontent.com/1827173/37713791-bc6f4bd0-2cf6-11e8-8dda-f9eeafb4cd59.png)

![image](https://user-images.githubusercontent.com/1827173/37713771-b0081278-2cf6-11e8-9779-8b31fd75c38d.png)

**Comment by thaisrigolon** [comment]
Ok. Issue homologada.
