### ISSUE TITLE
Título da página inicial

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#83]
A Thaís comentou (https://github.com/institutotim/wp-theme-mapasculturais/issues/69) que seria bom aumentar o título "Portal Mapas Culturais" na página inicial, mas agora ele quebrou linha.

**Comment by HeloMubarack** [comment]
Será possível realizar esse ajuste, pessoal?

**Comment by Nathlis** [comment]
Homologada.
