### ISSUE TITLE
Permissões do usuário "Instância"

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#85]
- [x] Retirar a permissão de inserir informação na linha do tempo para usuário da instância

- [x] Nos posts da Rede o usuário deve ter permissão de editar e adicionar posts somente na sua instância e não nas demais
![1](https://user-images.githubusercontent.com/18294515/37098769-7856b608-21fd-11e8-9403-ba56968fc469.png)

- [x] É possível adicionar a foto diretamente no painel do wordpress ou precisa estar associada ao site gravatar?

**Comment by cabelotaina** [comment]
@thaisrigolon faz um teste para ver se as permissões estão ok, eu cheguei a fazer algo e comitei para vocês em hml

**Comment by cabelotaina** [comment]
Precisa estar associado ao site gravatar.

**Comment by thaisrigolon** [comment]
- [ ] O usuário da instância ainda pode adicionar um evento na linha do tempo. É possível retirar esse botão da lateral?

![1](https://user-images.githubusercontent.com/18294515/37174848-863e1208-22f6-11e8-8148-d4015ff6a3af.png)

![2](https://user-images.githubusercontent.com/18294515/37174854-8a1dff00-22f6-11e8-915e-8fdcb3915e36.png)

- [ ] É possível não mostrar os outros post, somente os posts publicados pelo usuário da instância?
![2](https://user-images.githubusercontent.com/18294515/37174981-e0a0b228-22f6-11e8-89e6-0225e22c3881.png)

**Comment by cabelotaina** [comment]
Ola @vgeorge eu fiz algumas modificações faz um tempo mas para a @thaisrigolon conseguir vizualizar tem que dar um reset no papel instance:

![image](https://user-images.githubusercontent.com/1827173/37496586-1c2dbd90-2892-11e8-9886-787d987c8580.png)

Consegue ver isso?

**Comment by vgeorge** [comment]
@thaisrigolon O Maurílio mudou a autorização para edição de linha do tempo. Sobre a lista de posts da instância, o comportamento é exibir somente os posts próprios, se houver algum, ou exibir todos. Coloquei um post para instância de BH, fica assim:

<img width="1040" alt="captura de tela 2018-03-20 as 20 27 42" src="https://user-images.githubusercontent.com/329694/37681038-72c34172-2c7d-11e8-883f-35dca90230a0.png">

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
