### ISSUE TITLE
Área de contato _ Página da secretaria

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#86]
No painel de edição dos dados da secretaria há um campo para adicionar o e-mail dos membros da equipe, mas esse e-mail não aparece na página da secretaria...

![1](https://user-images.githubusercontent.com/18294515/37344349-ed22f028-26a8-11e8-9cfc-fc1768f4a91d.png)

![1](https://user-images.githubusercontent.com/18294515/37344378-f8128052-26a8-11e8-9007-4172ed13a86f.png)

É possível exibir o e-mail?

**Comment by vgeorge** [comment]
Se o e-mail for longo haverá quebra de linha, então coloquei um link para o endereço no nome da pessoa.

**Comment by thaisrigolon** [comment]
Ok.
