### ISSUE TITLE
Mapa do Site

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#87]
Como alteramos e configuramos os links disponíveis no rodapé que formam o mapa do site?

![1](https://user-images.githubusercontent.com/18294515/37347304-444dbac0-26b0-11e8-9431-d3ec955a71e0.png)

**Comment by vgeorge** [comment]
A configuração fica no menu "Aparência/Menus", acessível diretamente aqui:

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/nav-menus.php

Nesta página pode ser editado o cabeçalho e o rodapé.

**Comment by thaisrigolon** [comment]
Obrigada.
