### ISSUE TITLE
Melhorias e Dúvidas _ Home

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#88]
- [x] Deixar o sublinhado até o ponto final. Está passando um pouco:
![1](https://user-images.githubusercontent.com/18294515/37526430-190b0e48-290e-11e8-93db-a21cac203a0c.png)

- [x] No rodapé, padronizar o espaço das colunas. A coluna "Sobre a iniciativa" está muito pro lado.
![1](https://user-images.githubusercontent.com/18294515/37526868-4906514c-290f-11e8-8e2a-7405dd65ebcd.png)

**Dúvidas**

**1** É possível alterar os 4 ícones da home? Alteramos esses ícones para um novo padrão.
![1](https://user-images.githubusercontent.com/18294515/37526478-3cf79858-290e-11e8-85f1-155868b136a5.png)

**2** Na parte de Blog da rede podemos manejar o número que aparece? Gostaríamos de os 3 últimos posts.

**3** É possível deixar apenas duas notícias aparecendo e com um resumo das 3 linhas iniciais? 

**4** Podemos escolher quantas notícias aparecem na home?

**Comment by vgeorge** [comment]
@thaisrigolon, sobre as questões:

1. O ícones estão nesta imagem svg, vocês podem substituir direto ou me enviar nova versão: https://github.com/institutotim/wp-theme-mapasculturais/blob/to-validate/img/mc.svg
2. Já está em 3 posts;
3. Esta alteração não é muito simples e a seção estava aprovada, infelizmente não vamos conseguir alterar;
4. Está fixo em 1 com thumb e 2 sem thumb.

Marquei o @miguelpeixe para fazer as correções de front-end.

**Comment by cabelotaina** [comment]
Não tenho a menor ideia de como resolver essa issue... "Deixar o sublinhado até o ponto final. Está passando um pouco", cheguei a tentar ver se isso era algo que podemos alterar, mas pelo que entendi parecia algo que o css relaciona de maneira automagica.  @miguelpeixe alguma ideia?

**Comment by cabelotaina** [comment]
Acredito que aqui batemos em um limite da responsividade, a ideia do componente que usamos eh que ele deve estar desde o inicio da linha ate o final da linha e se auto ajudar dentro do espaço disponivel, sugiro fazer um teste vendo como o menu se adequa a diferentes resoluções. Nem sempre ele vai estar perfeito.

veja

![image](https://user-images.githubusercontent.com/1827173/37689983-05b1c482-2c87-11e8-99bd-e049086fc5c2.png)

![image](https://user-images.githubusercontent.com/1827173/37689990-104469ae-2c87-11e8-9a80-821561a247b3.png)

![image](https://user-images.githubusercontent.com/1827173/37690001-22b495aa-2c87-11e8-8a40-9916eeadde78.png)

![image](https://user-images.githubusercontent.com/1827173/37690013-2e038aba-2c87-11e8-957d-2fe8eaef66b3.png)

Sendo assim isso eh um efeito de como o componente esta se adaptando ao espaço disponivel.

**Comment by miguelpeixe** [comment]
Foi adicionado um espaçamento entre a parte do texto destacada (com linha) e o restante do texto da página inicial.

Também foi aplicada distribuição fixa de largura no menu do rodapé, além de uma pequena margem para melhorar leitura em resoluções menores.

**Comment by Nathlis** [comment]
Não é possível tirar o sublinhado?

**Comment by miguelpeixe** [comment]
Removido

**Comment by Nathlis** [comment]
Por favor retirar o espaçamento a mais entre "colaborativa e promove."

**Comment by miguelpeixe** [comment]
Feito

**Comment by Nathlis** [comment]
Aprovado
