### ISSUE TITLE
Melhorias e Dúvida _ Mapa da Rede

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#89]
- [x] Deixar o botão de + e - do zoom na cor preta.
![1](https://user-images.githubusercontent.com/18294515/37527330-913244c0-2910-11e8-8e9c-7073afa97481.png)

- [x] As sombras estão deslocadas no texto. Deixar cobrindo todo o texto.
![1](https://user-images.githubusercontent.com/18294515/37527514-f57e3c7c-2910-11e8-8f33-91d472620672.png)

- Dúvida:
É possível mudar os ícones da página do Mapa da Rede, conforme solicitado para a home?
![1](https://user-images.githubusercontent.com/18294515/37527422-c82bf41c-2910-11e8-893c-c33eb9410c03.png)

**Comment by cabelotaina** [comment]
corrigido, @vgeorge responda a duvida

**Comment by thaisrigolon** [comment]
@cabelotaina as alterações ainda não estão aparecendo..

**Comment by vgeorge** [comment]
Subi as alterações. Não vamos conseguir mudar os ícones, é algo que não é simples de ser feito no momento. @thaisrigolon

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
