### ISSUE TITLE
Design - Cabeçalho

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#9]

**Comment by miguelpeixe** [comment]
![home-hero](https://cloud.githubusercontent.com/assets/820752/24506189/0bc1a16a-1533-11e7-9b8c-4faf3f8cdbe7.jpg)

![pagina](https://cloud.githubusercontent.com/assets/820752/24506193/119f6f54-1533-11e7-9f9d-012dc2d0d3b4.jpg)

![mapa-rede](https://cloud.githubusercontent.com/assets/820752/24506200/163e5250-1533-11e7-9689-658db05379d0.jpg)

![perfil](https://cloud.githubusercontent.com/assets/820752/24506204/194f5d36-1533-11e7-99b7-830ecd83f1f3.jpg)

![comunidade](https://cloud.githubusercontent.com/assets/820752/24506205/1c500d28-1533-11e7-94f1-bb515e7d9e94.jpg)

A proposta aplica a cor azul clara como identidade principal do portal (cabeçalho da home, páginas institucionais e suporte). Para todas as áreas que dizem respeito à rede (perfil do mantenedor e mapa das instalações) a cor rosa foi aplicada, e para a comunidade (delibera) o bege.

Em todos os casos o cabeçalho da página se incorpora ao cabeçalho principal.

**Comment by thaisrigolon** [comment]
A gente consegue validar essa proposta de layout no wireframe criado ou só conseguimos validar pelas imagens do layout?

**Comment by miguelpeixe** [comment]
Por enquanto só pelas imagens

**Comment by miguelpeixe** [comment]
A nova proposta apresenta um design mais arrojado, alto contraste, cores vivas e utilizando técnicas de HTML5 canvas e animação svg ilustrando movimento e dinamismo da comunidade. A linha tracejada segue parte da identidade - remetendo ao projeto original - mas com uma proposta interativa e generativa.

A proposta do logo remete a um dos ícones de pin do projeto, mas com sobreposição e adaptações com as novas cores propostas.

Além disso, sugiro uma alteração do wireframe em relação ao texto de destaque abaixo do *hero*, como uma continuação do cabeçalho/hero na página inicial, apresentando de forma animada os recursos/funcionamento do Mapas Culturais.

http://portal-mapas.conexaobrasil.org/

![logo](https://cloud.githubusercontent.com/assets/820752/24816357/d0218210-1bae-11e7-9146-e045cbc78046.png)

![header](https://cloud.githubusercontent.com/assets/820752/24816365/da52622c-1bae-11e7-8012-5392256f5da0.png)

![home-main-text](https://cloud.githubusercontent.com/assets/820752/24816497/57f89296-1baf-11e7-9c44-de19834fbefe.png)

**Comment by thaisrigolon** [comment]
A nova proposta está muito boa, parabéns! Consideração inicial: deixar apenas a seta pra rolar pra baixo, sem o texto:
![1](https://cloud.githubusercontent.com/assets/18294515/24817722/0c60e266-1bb4-11e7-934c-8c84120e354f.png)

**Comment by miguelpeixe** [comment]
obrigado! removi o texto

**Comment by thaisrigolon** [comment]
- [x] No campo **Busque qualquer coisa** seria importante ter um box (pode ser uma leve mudança de cor) pra mostrar que não faz parte do menu. Pode manter o campo no mesmo local, mas precisa ter um leve destaque.

![1](https://cloud.githubusercontent.com/assets/18294515/25345644/f4bcf560-28eb-11e7-8bb4-aae22e14fee5.png)

Referências:

![1](https://cloud.githubusercontent.com/assets/18294515/25345495/aa4344b2-28eb-11e7-91ce-00b0518318af.png)

![2](https://cloud.githubusercontent.com/assets/18294515/25345499/ad755a26-28eb-11e7-8731-fbb30c55b0da.png)

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
