### ISSUE TITLE
Melhorias _ Home Notícias

### ISSUE THREAD

**Issue by thaisrigolon** [institutotim/wp-theme-mapasculturais#90]
- [ ] As páginas **Notícias** e **Blog da Rede** estão puxando os mesmos posts. Precisa separar notícias / blog da rede

- [ ] Nós conseguimos escolher o número de posts que aparecem na primeira página de Notícias?

- [ ] Alterar texto dos botões para: Anterior e Próxima
![1](https://user-images.githubusercontent.com/18294515/37532823-e7db2d6a-291e-11e8-9501-316e1cf207dd.png)

- [ ] É possível adicionar os números de páginas também ao final ou não?
![1](https://user-images.githubusercontent.com/18294515/37532842-f87a0380-291e-11e8-99c2-98a28dfbdf87.png)

**Comment by vgeorge** [comment]
@thaisrigolon foi criada uma issue em separada para o bug das listas https://github.com/institutotim/wp-theme-mapasculturais/issues/94

Sobre as outras questões:

2. Está como no padrão do wordpress, 5;
3. Feito;
4. Não, não havíamos considerado assim no design.

**Comment by thaisrigolon** [comment]
Ok, obrigada.
