### ISSUE TITLE
Qual branch usar para fazer testes de deploy do tema? 

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/wp-theme-mapasculturais#91]
### Cenário 1
1. Fiz uma instalação zerada de wp;
2. Instalei e habilitei o tema no branch `to-validate`;
3. Instalei os plugins requeridos;
4. Recebi essa home:
![selecao_085](https://user-images.githubusercontent.com/641411/37540956-a82e5930-2937-11e8-9f19-4fdf2553d9ac.png)
aferição de branch:
![selecao_086](https://user-images.githubusercontent.com/641411/37541157-47f0eb72-2938-11e8-9a9c-441780ad6cde.png)

### Cenário 2
1. Na mesma instalação, habilitei o tema no branch `master`
2. Recebi essa home:
![selecao_087](https://user-images.githubusercontent.com/641411/37541010-d25beb1e-2937-11e8-9dca-0e53a3b5d498.png)
Aferição de branch:
![selecao_088](https://user-images.githubusercontent.com/641411/37541160-4c78bf30-2938-11e8-9dbd-4ab05143ba9f.png)

### Pergunta
Qual branch devo tomar para fazer a validação técnica de entregas do tema? A branch `to-validate`, certo? 
A partir de que momento devo fazer o processo de instalação do zero para aferir as entregas? Devemos esperar mais antes de começar o processo? Acho que já podemos fazer né? A branch to-validate parece ok uma vez que a engine do menu já está operando pelo painel, a front-page já é setada corretamente, etc.

**Comment by vgeorge** [comment]
Felipe, o branch é esse mesmo. Não falta muita coisa para terminar, você pode ir testando sim. É preciso criar os menus para que apareçam corretamente, como nesta página:

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/nav-menus.php

Para que as páginas apareçam corretamente, é preciso que você crie páginas em branco que sigam os templates abaixo, sendo possível selecionar no dropdown do box do lado direito:

- Home page
- Community
- Network
- Support
- Partners

Aqui estão as páginas da homologação, para ter uma referência:

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/edit.php?post_type=page

**Comment by intrepidocabral** [comment]
ok!
