### ISSUE TITLE
Qual é a função 'instância'? onde está? 

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/wp-theme-mapasculturais#92]
Ao tentar adicionar um link de instalação, deparei-me com isso: 

![selecao_090](https://user-images.githubusercontent.com/641411/37542381-c27d9e22-293c-11e8-9964-e999f6f3c048.png)

O que quer dizer com função "instância"? É um content type? Onde isso é visto? Não achei aqui (vendo a branch `to-validate`): 
![captura de tela de 2018-03-16 17-10-08](https://user-images.githubusercontent.com/641411/37542468-111632f6-293d-11e8-8cf6-8d306e9c876a.png)

**Comment by vgeorge** [comment]
É um tipo de usuário:

http://hmg.mapasculturais.medialab.ufg.br/wp-admin/users.php?role=instance

**Comment by intrepidocabral** [comment]
ok! resolvido.
