### ISSUE TITLE
Sombras muito deslocadas na página da comunidade

### ISSUE THREAD

**Issue by vgeorge** [institutotim/wp-theme-mapasculturais#93]
http://hmg.mapasculturais.medialab.ufg.br/comunidade/

![image](https://user-images.githubusercontent.com/329694/37686183-36845366-2c8e-11e8-9300-f9986f4af21e.png)

**Comment by cabelotaina** [comment]
Corrigido

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
