### ISSUE TITLE
Título página BLOG DA REDE

### ISSUE THREAD

**Issue by Nathlis** [institutotim/wp-theme-mapasculturais#95]
- [ ] Trocar o nome de POST DA REDE para **BLOG DA REDE**:

![7](https://user-images.githubusercontent.com/18741130/39594427-0ed66cce-4ee3-11e8-9df9-bcafc4845d87.png)

http://hmg.mapasculturais.medialab.ufg.br/blog-da-rede/

![8](https://user-images.githubusercontent.com/18741130/39594446-16ce36c8-4ee3-11e8-8bb1-f344ab9e30da.png)

**Comment by vgeorge** [comment]
Feito.

**Comment by Nathlis** [comment]
Homologada.
